<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Analyse og visualisering af biologiske datasæt - 2023</title>
  <meta name="description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  <meta name="generator" content="bookdown 0.33 and GitBook 2.6.7" />

  <meta property="og:title" content="Analyse og visualisering af biologiske datasæt - 2023" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Analyse og visualisering af biologiske datasæt - 2023" />
  
  <meta name="twitter:description" content="Course materials for Analyse og visualisering af biologiske datasæt 2022" />
  

<meta name="author" content="Sarah Rennie" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="rmarkdown.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Visualisering kursus</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Grundlæggende R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#inledning-til-kapitel"><i class="fa fa-check"></i><b>1.1</b> Inledning til kapitel</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#rstudio"><i class="fa fa-check"></i><b>1.2</b> RStudio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#de-forskellige-vinduer-i-rstudio"><i class="fa fa-check"></i><b>1.2.1</b> De forskellige vinduer i RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#working-directory"><i class="fa fa-check"></i><b>1.3</b> Working directory</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#r-pakker"><i class="fa fa-check"></i><b>1.4</b> R pakker</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#hvor-kommer-vores-data-fra"><i class="fa fa-check"></i><b>1.5</b> Hvor kommer vores data fra?</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="index.html"><a href="index.html#indbyggede-datasæt"><i class="fa fa-check"></i><b>1.5.1</b> Indbyggede datasæt</a></li>
<li class="chapter" data-level="1.5.2" data-path="index.html"><a href="index.html#importering-af-data-fra-.txt-fil"><i class="fa fa-check"></i><b>1.5.2</b> Importering af data fra .txt fil</a></li>
<li class="chapter" data-level="1.5.3" data-path="index.html"><a href="index.html#importering-af-data-fra-excel"><i class="fa fa-check"></i><b>1.5.3</b> Importering af data fra Excel</a></li>
<li class="chapter" data-level="1.5.4" data-path="index.html"><a href="index.html#kaggle"><i class="fa fa-check"></i><b>1.5.4</b> Kaggle</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#beregninger-i-r"><i class="fa fa-check"></i><b>1.6</b> Beregninger i R</a>
<ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#vectorer"><i class="fa fa-check"></i><b>1.6.1</b> Vectorer</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#datatyper"><i class="fa fa-check"></i><b>1.6.2</b> datatyper</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="index.html"><a href="index.html#dataframes"><i class="fa fa-check"></i><b>1.7</b> Dataframes</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="index.html"><a href="index.html#delmængder-af-dataframes"><i class="fa fa-check"></i><b>1.7.1</b> Delmængder af dataframes</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="index.html"><a href="index.html#ifelse"><i class="fa fa-check"></i><b>1.8</b> If/else</a></li>
<li class="chapter" data-level="1.9" data-path="index.html"><a href="index.html#loops"><i class="fa fa-check"></i><b>1.9</b> Loops</a></li>
<li class="chapter" data-level="1.10" data-path="index.html"><a href="index.html#descriptive-statistics"><i class="fa fa-check"></i><b>1.10</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="index.html"><a href="index.html#simulere-data-fra-den-normale-fordeling"><i class="fa fa-check"></i><b>1.10.1</b> Simulere data fra den normale fordeling</a></li>
<li class="chapter" data-level="1.10.2" data-path="index.html"><a href="index.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>1.10.2</b> Measures of central tendency</a></li>
<li class="chapter" data-level="1.10.3" data-path="index.html"><a href="index.html#tapply"><i class="fa fa-check"></i><b>1.10.3</b> <code>tapply()</code></a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="index.html"><a href="index.html#statistike-tester"><i class="fa fa-check"></i><b>1.11</b> Statistike tester</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="index.html"><a href="index.html#p-værdien"><i class="fa fa-check"></i><b>1.11.1</b> P-værdien</a></li>
<li class="chapter" data-level="1.11.2" data-path="index.html"><a href="index.html#korrelation"><i class="fa fa-check"></i><b>1.11.2</b> Korrelation</a></li>
<li class="chapter" data-level="1.11.3" data-path="index.html"><a href="index.html#test-for-uafhængighed-chi-sq-test"><i class="fa fa-check"></i><b>1.11.3</b> Test for uafhængighed (chi-sq test)</a></li>
<li class="chapter" data-level="1.11.4" data-path="index.html"><a href="index.html#sample-t-test"><i class="fa fa-check"></i><b>1.11.4</b> 1 sample t-test</a></li>
<li class="chapter" data-level="1.11.5" data-path="index.html"><a href="index.html#sample-t-test-1"><i class="fa fa-check"></i><b>1.11.5</b> 2-sample t-test</a></li>
<li class="chapter" data-level="1.11.6" data-path="index.html"><a href="index.html#paired-t-test"><i class="fa fa-check"></i><b>1.11.6</b> Paired t-test</a></li>
<li class="chapter" data-level="1.11.7" data-path="index.html"><a href="index.html#anova-variansanalyse"><i class="fa fa-check"></i><b>1.11.7</b> ANOVA (variansanalyse)</a></li>
<li class="chapter" data-level="1.11.8" data-path="index.html"><a href="index.html#lineær-regression"><i class="fa fa-check"></i><b>1.11.8</b> Lineær regression</a></li>
<li class="chapter" data-level="1.11.9" data-path="index.html"><a href="index.html#r-squared-coefficient-of-determination"><i class="fa fa-check"></i><b>1.11.9</b> R-squared coefficient of determination</a></li>
<li class="chapter" data-level="1.11.10" data-path="index.html"><a href="index.html#antagelser---lineær-regression"><i class="fa fa-check"></i><b>1.11.10</b> Antagelser - lineær regression</a></li>
<li class="chapter" data-level="1.11.11" data-path="index.html"><a href="index.html#multiple-lineær-regression"><i class="fa fa-check"></i><b>1.11.11</b> Multiple lineær regression</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="index.html"><a href="index.html#problemstillinger"><i class="fa fa-check"></i><b>1.12</b> Problemstillinger</a>
<ul>
<li class="chapter" data-level="1.12.1" data-path="index.html"><a href="index.html#quiz---basics"><i class="fa fa-check"></i><b>1.12.1</b> Quiz - Basics</a></li>
<li class="chapter" data-level="1.12.2" data-path="index.html"><a href="index.html#grundlæggende-r"><i class="fa fa-check"></i><b>1.12.2</b> Grundlæggende R</a></li>
<li class="chapter" data-level="1.12.3" data-path="index.html"><a href="index.html#kort-analyse-med-reaktionstider"><i class="fa fa-check"></i><b>1.12.3</b> Kort analyse med reaktionstider</a></li>
<li class="chapter" data-level="1.12.4" data-path="index.html"><a href="index.html#øvelse-med-co2"><i class="fa fa-check"></i><b>1.12.4</b> Øvelse med CO2</a></li>
<li class="chapter" data-level="1.12.5" data-path="index.html"><a href="index.html#ekstra-øvelser-med-statistik-tests"><i class="fa fa-check"></i><b>1.12.5</b> Ekstra øvelser med statistik tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>2</b> Introduktion til R Markdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rmarkdown.html"><a href="rmarkdown.html#hvad-er-r-markdown"><i class="fa fa-check"></i><b>2.1</b> Hvad er R Markdown?</a></li>
<li class="chapter" data-level="2.2" data-path="rmarkdown.html"><a href="rmarkdown.html#installere-r-markdown"><i class="fa fa-check"></i><b>2.2</b> Installere R Markdown</a></li>
<li class="chapter" data-level="2.3" data-path="rmarkdown.html"><a href="rmarkdown.html#videodemonstrationer"><i class="fa fa-check"></i><b>2.3</b> Videodemonstrationer</a></li>
<li class="chapter" data-level="2.4" data-path="rmarkdown.html"><a href="rmarkdown.html#oprette-et-nyt-dokument-i-r-markdown"><i class="fa fa-check"></i><b>2.4</b> Oprette et nyt dokument i R Markdown</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="rmarkdown.html"><a href="rmarkdown.html#yaml"><i class="fa fa-check"></i><b>2.4.1</b> YAML</a></li>
<li class="chapter" data-level="2.4.2" data-path="rmarkdown.html"><a href="rmarkdown.html#globale-options"><i class="fa fa-check"></i><b>2.4.2</b> Globale options</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="rmarkdown.html"><a href="rmarkdown.html#skrive-baseret-tekst"><i class="fa fa-check"></i><b>2.5</b> Skrive baseret tekst</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="rmarkdown.html"><a href="rmarkdown.html#headers"><i class="fa fa-check"></i><b>2.5.1</b> Headers</a></li>
<li class="chapter" data-level="2.5.2" data-path="rmarkdown.html"><a href="rmarkdown.html#liste"><i class="fa fa-check"></i><b>2.5.2</b> liste</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="rmarkdown.html"><a href="rmarkdown.html#knitte-kode"><i class="fa fa-check"></i><b>2.6</b> Knitte kode</a></li>
<li class="chapter" data-level="2.7" data-path="rmarkdown.html"><a href="rmarkdown.html#kode-chunks"><i class="fa fa-check"></i><b>2.7</b> Kode chunks</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="rmarkdown.html"><a href="rmarkdown.html#et-godt-råd-når-man-arbejder-med-chunks"><i class="fa fa-check"></i><b>2.7.1</b> Et godt råd når man arbejder med chunks</a></li>
<li class="chapter" data-level="2.7.2" data-path="rmarkdown.html"><a href="rmarkdown.html#chunk-indstillinger"><i class="fa fa-check"></i><b>2.7.2</b> Chunk indstillinger</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="rmarkdown.html"><a href="rmarkdown.html#r-beregninger-inden-for-teksten-i-dokumentet-inline-code"><i class="fa fa-check"></i><b>2.8</b> R beregninger inden for teksten i dokumentet (‘inline code’)</a></li>
<li class="chapter" data-level="2.9" data-path="rmarkdown.html"><a href="rmarkdown.html#working-directory-1"><i class="fa fa-check"></i><b>2.9</b> Working directory</a></li>
<li class="chapter" data-level="2.10" data-path="rmarkdown.html"><a href="rmarkdown.html#matematik"><i class="fa fa-check"></i><b>2.10</b> Matematik</a></li>
<li class="chapter" data-level="2.11" data-path="rmarkdown.html"><a href="rmarkdown.html#problemstillinger-1"><i class="fa fa-check"></i><b>2.11</b> Problemstillinger</a></li>
<li class="chapter" data-level="2.12" data-path="rmarkdown.html"><a href="rmarkdown.html#færdig-for-i-dag-og-næste-gang"><i class="fa fa-check"></i><b>2.12</b> Færdig for i dag og næste gang</a></li>
<li class="chapter" data-level="2.13" data-path="rmarkdown.html"><a href="rmarkdown.html#ekstra-links"><i class="fa fa-check"></i><b>2.13</b> Ekstra links</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visual1.html"><a href="visual1.html"><i class="fa fa-check"></i><b>3</b> Visualisering - ggplot2 dag 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="visual1.html"><a href="visual1.html#inledning-og-videoer"><i class="fa fa-check"></i><b>3.1</b> Inledning og videoer</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="visual1.html"><a href="visual1.html#læringsmålene-for-dag-1"><i class="fa fa-check"></i><b>3.1.1</b> Læringsmålene for dag 1</a></li>
<li class="chapter" data-level="3.1.2" data-path="visual1.html"><a href="visual1.html#hvad-er-ggplot2"><i class="fa fa-check"></i><b>3.1.2</b> Hvad er <strong>ggplot2</strong>?</a></li>
<li class="chapter" data-level="3.1.3" data-path="visual1.html"><a href="visual1.html#brugen-af-materialerne"><i class="fa fa-check"></i><b>3.1.3</b> Brugen af materialerne</a></li>
<li class="chapter" data-level="3.1.4" data-path="visual1.html"><a href="visual1.html#video-ressourcer"><i class="fa fa-check"></i><b>3.1.4</b> Video ressourcer</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="visual1.html"><a href="visual1.html#transition-fra-base-r-til-ggplot2"><i class="fa fa-check"></i><b>3.2</b> Transition fra base R til ggplot2</a></li>
<li class="chapter" data-level="3.3" data-path="visual1.html"><a href="visual1.html#vores-første-ggplot"><i class="fa fa-check"></i><b>3.3</b> Vores første ggplot</a></li>
<li class="chapter" data-level="3.4" data-path="visual1.html"><a href="visual1.html#lidt-om-ggplot2"><i class="fa fa-check"></i><b>3.4</b> Lidt om ggplot2</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="visual1.html"><a href="visual1.html#syntax"><i class="fa fa-check"></i><b>3.4.1</b> Syntax</a></li>
<li class="chapter" data-level="3.4.2" data-path="visual1.html"><a href="visual1.html#hvad-betyder-egentlig-grammar-of-graphics"><i class="fa fa-check"></i><b>3.4.2</b> Hvad betyder egentlig grammar of graphics?</a></li>
<li class="chapter" data-level="3.4.3" data-path="visual1.html"><a href="visual1.html#globale-versus-lokale-æstetik"><i class="fa fa-check"></i><b>3.4.3</b> Globale versus lokale æstetik</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="visual1.html"><a href="visual1.html#specificere-etiketter-og-titel"><i class="fa fa-check"></i><b>3.5</b> Specificere etiketter og titel</a></li>
<li class="chapter" data-level="3.6" data-path="visual1.html"><a href="visual1.html#ændre-farver"><i class="fa fa-check"></i><b>3.6</b> Ændre farver</a></li>
<li class="chapter" data-level="3.7" data-path="visual1.html"><a href="visual1.html#ændre-tema"><i class="fa fa-check"></i><b>3.7</b> Ændre tema</a></li>
<li class="chapter" data-level="3.8" data-path="visual1.html"><a href="visual1.html#forskellige-geoms"><i class="fa fa-check"></i><b>3.8</b> Forskellige geoms</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="visual1.html"><a href="visual1.html#boxplot-geom_box"><i class="fa fa-check"></i><b>3.8.1</b> Boxplot (<code>geom_box</code>)</a></li>
<li class="chapter" data-level="3.8.2" data-path="visual1.html"><a href="visual1.html#barplot-geom_bar"><i class="fa fa-check"></i><b>3.8.2</b> Barplot (<code>geom_bar</code>)</a></li>
<li class="chapter" data-level="3.8.3" data-path="visual1.html"><a href="visual1.html#histogram-geom_histogram"><i class="fa fa-check"></i><b>3.8.3</b> Histogram (<code>geom_histogram</code>)</a></li>
<li class="chapter" data-level="3.8.4" data-path="visual1.html"><a href="visual1.html#density-geom_density"><i class="fa fa-check"></i><b>3.8.4</b> Density (<code>geom_density</code>)</a></li>
<li class="chapter" data-level="3.8.5" data-path="visual1.html"><a href="visual1.html#line-plot-geom_line"><i class="fa fa-check"></i><b>3.8.5</b> Line plot (<code>geom_line()</code>)</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="visual1.html"><a href="visual1.html#troubleshooting"><i class="fa fa-check"></i><b>3.9</b> Troubleshooting</a></li>
<li class="chapter" data-level="3.10" data-path="visual1.html"><a href="visual1.html#problemstillinger-2"><i class="fa fa-check"></i><b>3.10</b> Problemstillinger</a></li>
<li class="chapter" data-level="3.11" data-path="visual1.html"><a href="visual1.html#næste-gang"><i class="fa fa-check"></i><b>3.11</b> Næste gang</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="visual2.html"><a href="visual2.html"><i class="fa fa-check"></i><b>4</b> Visualisering - ggplot2 dag 2</a>
<ul>
<li class="chapter" data-level="4.1" data-path="visual2.html"><a href="visual2.html#indledning-og-videoer"><i class="fa fa-check"></i><b>4.1</b> Indledning og videoer</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="visual2.html"><a href="visual2.html#læringsmålene"><i class="fa fa-check"></i><b>4.1.1</b> Læringsmålene</a></li>
<li class="chapter" data-level="4.1.2" data-path="visual2.html"><a href="visual2.html#video-ressourcer-1"><i class="fa fa-check"></i><b>4.1.2</b> Video ressourcer</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="visual2.html"><a href="visual2.html#koordinat-systemer"><i class="fa fa-check"></i><b>4.2</b> Koordinat systemer</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="visual2.html"><a href="visual2.html#zoom-coord_cartesian-expand_limits"><i class="fa fa-check"></i><b>4.2.1</b> Zoom (<code>coord_cartesian()</code>, <code>expand_limits()</code>)</a></li>
<li class="chapter" data-level="4.2.2" data-path="visual2.html"><a href="visual2.html#transformering-af-akserne---log-sqrt-osv-scale_x_continuous."><i class="fa fa-check"></i><b>4.2.2</b> Transformering af akserne - log, sqrt osv (<code>scale_x_continuous</code>).</a></li>
<li class="chapter" data-level="4.2.3" data-path="visual2.html"><a href="visual2.html#flip-coordinates-coord_flip"><i class="fa fa-check"></i><b>4.2.3</b> Flip coordinates (<code>coord_flip</code>)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="visual2.html"><a href="visual2.html#mere-om-farver-og-punkt-former"><i class="fa fa-check"></i><b>4.3</b> Mere om farver og punkt former</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="visual2.html"><a href="visual2.html#automatisk-farver"><i class="fa fa-check"></i><b>4.3.1</b> Automatisk farver</a></li>
<li class="chapter" data-level="4.3.2" data-path="visual2.html"><a href="visual2.html#manuelle-farver"><i class="fa fa-check"></i><b>4.3.2</b> Manuelle farver</a></li>
<li class="chapter" data-level="4.3.3" data-path="visual2.html"><a href="visual2.html#punkt-former"><i class="fa fa-check"></i><b>4.3.3</b> Punkt former</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="visual2.html"><a href="visual2.html#annotations-geom_text"><i class="fa fa-check"></i><b>4.4</b> Annotations (<code>geom_text</code>)</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="visual2.html"><a href="visual2.html#tilføjelse-af-labels-direkte-på-plottet."><i class="fa fa-check"></i><b>4.4.1</b> Tilføjelse af labels direkte på plottet.</a></li>
<li class="chapter" data-level="4.4.2" data-path="visual2.html"><a href="visual2.html#pakken-ggrepel-for-at-tilføje-tekst-labeller"><i class="fa fa-check"></i><b>4.4.2</b> Pakken <code>ggrepel</code> for at tilføje tekst labeller</a></li>
<li class="chapter" data-level="4.4.3" data-path="visual2.html"><a href="visual2.html#tilføjelse-af-rektangler-i-regioner-af-interesse-annotate"><i class="fa fa-check"></i><b>4.4.3</b> Tilføjelse af rektangler i regioner af interesse (<code>annotate</code>)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="visual2.html"><a href="visual2.html#adskille-plots-med-facets-facet_gridfacet_wrap"><i class="fa fa-check"></i><b>4.5</b> Adskille plots med facets (<code>facet_grid</code>/<code>facet_wrap</code>)</a></li>
<li class="chapter" data-level="4.6" data-path="visual2.html"><a href="visual2.html#gemme-dit-plot"><i class="fa fa-check"></i><b>4.6</b> Gemme dit plot</a></li>
<li class="chapter" data-level="4.7" data-path="visual2.html"><a href="visual2.html#problemstillinger-3"><i class="fa fa-check"></i><b>4.7</b> Problemstillinger</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>5</b> Bearbejdning dag 1</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data.html"><a href="data.html#hvad-er-tidyverse"><i class="fa fa-check"></i><b>5.1</b> Hvad er Tidyverse?</a></li>
<li class="chapter" data-level="5.2" data-path="data.html"><a href="data.html#video-ressourcer-2"><i class="fa fa-check"></i><b>5.2</b> Video ressourcer</a></li>
<li class="chapter" data-level="5.3" data-path="data.html"><a href="data.html#oversigt-over-pakker"><i class="fa fa-check"></i><b>5.3</b> Oversigt over pakker</a></li>
<li class="chapter" data-level="5.4" data-path="data.html"><a href="data.html#principper-for-tidy-data"><i class="fa fa-check"></i><b>5.4</b> Principper for ‘tidy data’</a></li>
<li class="chapter" data-level="5.5" data-path="data.html"><a href="data.html#lidt-om-tibbles"><i class="fa fa-check"></i><b>5.5</b> Lidt om <code>tibbles</code></a></li>
<li class="chapter" data-level="5.6" data-path="data.html"><a href="data.html#transition-fra-base-r-til-tidyverse"><i class="fa fa-check"></i><b>5.6</b> Transition fra base-R til tidyverse</a>
<ul>
<li class="chapter" data-level="5.6.1" data-path="data.html"><a href="data.html#om-titanic-datasættet"><i class="fa fa-check"></i><b>5.6.1</b> Om <strong>Titanic</strong> datasættet</a></li>
<li class="chapter" data-level="5.6.2" data-path="data.html"><a href="data.html#titanic-rengøring"><i class="fa fa-check"></i><b>5.6.2</b> Titanic: Rengøring</a></li>
<li class="chapter" data-level="5.6.3" data-path="data.html"><a href="data.html#pipe"><i class="fa fa-check"></i><b>5.6.3</b> Pipe</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data.html"><a href="data.html#bearbejdning-af-data-dplyr"><i class="fa fa-check"></i><b>5.7</b> Bearbejdning af data: <code>dplyr</code></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="data.html"><a href="data.html#dplyr-verbs-select"><i class="fa fa-check"></i><b>5.7.1</b> dplyr verbs: <code>select()</code></a></li>
<li class="chapter" data-level="5.7.2" data-path="data.html"><a href="data.html#dplyr-verbs-filter"><i class="fa fa-check"></i><b>5.7.2</b> dplyr verbs: <code>filter()</code></a></li>
<li class="chapter" data-level="5.7.3" data-path="data.html"><a href="data.html#sammenligningsoperatorer"><i class="fa fa-check"></i><b>5.7.3</b> Sammenligningsoperatorer</a></li>
<li class="chapter" data-level="5.7.4" data-path="data.html"><a href="data.html#kombinere-filter-og-select"><i class="fa fa-check"></i><b>5.7.4</b> Kombinere <code>filter()</code> og <code>select()</code></a></li>
<li class="chapter" data-level="5.7.5" data-path="data.html"><a href="data.html#dplyr-verbs-mutate"><i class="fa fa-check"></i><b>5.7.5</b> dplyr verbs: <code>mutate()</code></a></li>
<li class="chapter" data-level="5.7.6" data-path="data.html"><a href="data.html#rename"><i class="fa fa-check"></i><b>5.7.6</b> <code>rename()</code></a></li>
<li class="chapter" data-level="5.7.7" data-path="data.html"><a href="data.html#dplyr-verbs-recode"><i class="fa fa-check"></i><b>5.7.7</b> dplyr verbs: <code>recode()</code></a></li>
<li class="chapter" data-level="5.7.8" data-path="data.html"><a href="data.html#dplyr-verbs-arrange"><i class="fa fa-check"></i><b>5.7.8</b> dplyr verbs: <code>arrange()</code></a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="data.html"><a href="data.html#visualisering-bruge-som-input-i-ggplot2"><i class="fa fa-check"></i><b>5.8</b> Visualisering: bruge som input i ggplot2</a></li>
<li class="chapter" data-level="5.9" data-path="data.html"><a href="data.html#misc-funktioner-som-er-nyttige-at-vide"><i class="fa fa-check"></i><b>5.9</b> Misc funktioner som er nyttige at vide</a>
<ul>
<li class="chapter" data-level="5.9.1" data-path="data.html"><a href="data.html#pull"><i class="fa fa-check"></i><b>5.9.1</b> Pull</a></li>
<li class="chapter" data-level="5.9.2" data-path="data.html"><a href="data.html#slice"><i class="fa fa-check"></i><b>5.9.2</b> Slice</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="data.html"><a href="data.html#problemstillinger-4"><i class="fa fa-check"></i><b>5.10</b> Problemstillinger</a></li>
<li class="chapter" data-level="5.11" data-path="data.html"><a href="data.html#kommentarer"><i class="fa fa-check"></i><b>5.11</b> Kommentarer</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html"><i class="fa fa-check"></i><b>6</b> Bearbejdning dag 2</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#indledning-og-læringsmålene"><i class="fa fa-check"></i><b>6.1</b> Indledning og læringsmålene</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#læringsmålene-1"><i class="fa fa-check"></i><b>6.1.1</b> Læringsmålene</a></li>
<li class="chapter" data-level="6.1.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#videoer"><i class="fa fa-check"></i><b>6.1.2</b> Videoer</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#group_by-med-summarise-i-dplyr-pakken"><i class="fa fa-check"></i><b>6.2</b> <code>group_by()</code> med <code>summarise()</code> i dplyr-pakken</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#reference-af-summarise-funktioner"><i class="fa fa-check"></i><b>6.2.1</b> Reference af <code>summarise()</code>-funktioner</a></li>
<li class="chapter" data-level="6.2.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#flere-summeringsstatistikker-på-én-gang"><i class="fa fa-check"></i><b>6.2.2</b> Flere summeringsstatistikker på én gang</a></li>
<li class="chapter" data-level="6.2.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#mere-avanceret-group_by"><i class="fa fa-check"></i><b>6.2.3</b> Mere avanceret <code>group_by()</code></a></li>
<li class="chapter" data-level="6.2.4" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#funktionen-ungroup"><i class="fa fa-check"></i><b>6.2.4</b> Funktionen <code>ungroup()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#pivot_longerpivot_wider-med-tidyr-pakken"><i class="fa fa-check"></i><b>6.3</b> <code>pivot_longer()</code>/<code>pivot_wider()</code> med Tidyr-pakken</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#tidyr-pakke---oversigt"><i class="fa fa-check"></i><b>6.3.1</b> Tidyr pakke - oversigt</a></li>
<li class="chapter" data-level="6.3.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#wide---long-med-pivot_longer"><i class="fa fa-check"></i><b>6.3.2</b> Wide -&gt; Long med <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="6.3.3" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#separate"><i class="fa fa-check"></i><b>6.3.3</b> <code>separate()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#eksempel-titanic-opsummeringsstatistikker"><i class="fa fa-check"></i><b>6.4</b> Eksempel: Titanic opsummeringsstatistikker</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#demonstration-af-pivot_wider"><i class="fa fa-check"></i><b>6.4.1</b> Demonstration af <code>pivot_wider()</code></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#left_join-forbinde-dataframes"><i class="fa fa-check"></i><b>6.5</b> <code>left_join()</code>: forbinde dataframes</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#funktionen-left_join-fra-dplyr-pakken"><i class="fa fa-check"></i><b>6.5.1</b> Funktionen <code>left_join()</code> fra dplyr-pakken</a></li>
<li class="chapter" data-level="6.5.2" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#anvend-left_join-for-vores-datasæt."><i class="fa fa-check"></i><b>6.5.2</b> Anvend <code>left_join()</code> for vores datasæt.</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#problemstillinger-5"><i class="fa fa-check"></i><b>6.6</b> Problemstillinger</a></li>
<li class="chapter" data-level="6.7" data-path="bearbejdning-dag-2.html"><a href="bearbejdning-dag-2.html#ekstra-links-1"><i class="fa fa-check"></i><b>6.7</b> Ekstra links</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html"><i class="fa fa-check"></i><b>7</b> Functional programming med purrr-pakken</a>
<ul>
<li class="chapter" data-level="7.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#inledning-og-læringsmålene"><i class="fa fa-check"></i><b>7.1</b> Inledning og læringsmålene</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#læringsmål"><i class="fa fa-check"></i><b>7.1.1</b> Læringsmål</a></li>
<li class="chapter" data-level="7.1.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#videorressourcer"><i class="fa fa-check"></i><b>7.1.2</b> Videorressourcer</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#iterative-processer-med-map-funktioner"><i class="fa fa-check"></i><b>7.2</b> Iterative processer med <code>map()</code> funktioner</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#introduktion-til-map-funktioner"><i class="fa fa-check"></i><b>7.2.1</b> Introduktion til <code>map()</code> funktioner</a></li>
<li class="chapter" data-level="7.2.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#reference-for-de-forskellige-map-funktioner"><i class="fa fa-check"></i><b>7.2.2</b> Reference for de forskellige map-funktioner</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#brugerdefinerede-funktioner"><i class="fa fa-check"></i><b>7.3</b> Brugerdefinerede funktioner</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#simple-funktioner"><i class="fa fa-check"></i><b>7.3.1</b> Simple funktioner</a></li>
<li class="chapter" data-level="7.3.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#brugerdefinerede-funktioner-med-mapping"><i class="fa fa-check"></i><b>7.3.2</b> Brugerdefinerede funktioner med mapping</a></li>
<li class="chapter" data-level="7.3.3" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#effekten-af-map-på-andre-datatyper"><i class="fa fa-check"></i><b>7.3.3</b> Effekten af <code>map</code> på andre datatyper</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#nesting-med-nest"><i class="fa fa-check"></i><b>7.4</b> Nesting med <code>nest()</code></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#anvendelse-af-map-med-nested-data"><i class="fa fa-check"></i><b>7.4.1</b> Anvendelse af map() med nested data</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#andre-brugbar-purrr"><i class="fa fa-check"></i><b>7.5</b> Andre brugbar purrr</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#map2-funktion-for-flere-inputs"><i class="fa fa-check"></i><b>7.5.1</b> <code>map2()</code> funktion for flere inputs</a></li>
<li class="chapter" data-level="7.5.2" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#transformering-af-numeriske-variabler"><i class="fa fa-check"></i><b>7.5.2</b> Transformering af numeriske variabler</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#problemstillinger-6"><i class="fa fa-check"></i><b>7.6</b> Problemstillinger</a></li>
<li class="chapter" data-level="7.7" data-path="functional-programming-med-purrr-pakken.html"><a href="functional-programming-med-purrr-pakken.html#ekstra-notater-og-næste-gang"><i class="fa fa-check"></i><b>7.7</b> Ekstra notater og næste gang</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analyse og visualisering af biologiske datasæt - 2023</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Analyse og visualisering af biologiske datasæt - 2023</h1>
<p class="author"><em>Sarah Rennie</em></p>
<p class="date"><em>Last updated: 2023-05-14</em></p>
</div>
<div id="baser" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Grundlæggende R<a href="index.html#baser" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>“Det er ikke, fordi noget er svært, at vi ikke tør, det er, fordi vi ikke tør, at noget er svært” - Seneca</p>
<div id="inledning-til-kapitel" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Inledning til kapitel<a href="index.html#inledning-til-kapitel" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Først og fremmest, velkommen til kurset! Det her dokument er kursusnotaterne, som indeholder bla. videoer, forklaringer og problemstillinger, og jeg opdaterer dem løbende gennem hele forløbet. Vær opmærksom på, at der også vil være flere dokumenter på Absalon vedrørende forelæsninger, workshops og løsningerne til øvelserne.</p>
<p>I dette kapitel opsummerer jeg nogle grundlæggende elementer inden for R og statistik, der betragtes som forudsætninger i dette kursus. Selvom vi i kurset skifter hurtigt over til tidyverse-pakken, som erstatter en stor del af funktionaliteten fra base-R, er det stadig vigtigt at have et grundlæggende kendskab til hvordan tingene fungerer i base-R. Hvis du har begrænset erfaring med base-R, anbefaler jeg, at du bruger ekstra tid ud over de første mødegange for at nå det nødvendige niveau.</p>
<p>For at bestå kurset forventes det ikke, at du kender til alle detaljer og teorier bag de statistiske metoder, men at du kan anvende dem hensigtsmæssigt i praksis i R og fortolke resultaterne korrekte. Der vil være masser af muligheder for at øve dig I at anvende statistik hele vejen gennem kurset, og under eksamen vil jeg ikke stille spørgsmål om metoder, der ikke er dækket i de forskellige øvelser (herunder workshop-opgaver). Lineær regression vil også blive gennemgået i forelæsningerne så vær ikke bekymret hvis du ikke har set det hele før.</p>
<p>Se gerne også “Quiz - grundlæggende” på Absalon for at tjekke din forståelse og udfylde eventuelle huller i din viden (OBS: Quizzen er tilgængelig kort tid inden kursets start).</p>
</div>
<div id="rstudio" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> RStudio<a href="index.html#rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Vi kommer fremadrettet til at være afhængig af RStudio til at arbejde med bl.a. R Markdown dokumenter. Kendskab til R Markdown er emnet i vores næste lektion og jeg går ud fra, at du ikke har benyttet det før.</p>
<p>Det allerførste du bør gør, hvis du ikke har installeret RStudio på din computer, er at downloade det gratis på nettet:</p>
<p><a href="https://www.rstudio.com/products/rstudio/download/#download" class="uri">https://www.rstudio.com/products/rstudio/download/#download</a></p>
<p>Følg venligst RStudios egne anvisninger til at få det installeret. Bemærk, at installering af RStudio er ikke den samme som at have R installeret på din computer - man skal installere dem begge to (man kan bruge R uden RStudio men ikke omvendt.</p>
<div id="de-forskellige-vinduer-i-rstudio" class="section level3 hasAnchor" number="1.2.1">
<h3><span class="header-section-number">1.2.1</span> De forskellige vinduer i RStudio<a href="index.html#de-forskellige-vinduer-i-rstudio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Du kan læse følgende for at lære de fire forskellige vinduer i RStudio at kende:</p>
<p><a href="https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html" class="uri">https://bookdown.org/ndphillips/YaRrr/the-four-rstudio-windows.html</a></p>
<p>Her er et kort oversigt:</p>
<ul>
<li>Man skriver kode i <strong>Source</strong> (øverst til venstre)</li>
<li>Man kører kode ved at tryk CMD+ENTER (eller WIN-KEY+ENTER)</li>
<li>Koder køres ind i <strong>Console</strong> (som plejer at være nederst til venstre, selvom det er øverst til højere i billedet). Man kan også skrive koder direkte i Console, men det ikke anbefales generelt, når koden ikke bliver gemt.</li>
<li><strong>Environment</strong> - her kan man se blandt andet, alle objekter i Workspace.</li>
</ul>
</div>
</div>
<div id="working-directory" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Working directory<a href="index.html#working-directory" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Når man arbejder på et projekt, er det ofte nyttigt at vide, den <em>working directory</em> som R arbejder fra - det er den mappe, hvor R forsøger at åbne eller gemme filer fra, medmindre man angiver et andet sted.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="index.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>() <span class="co">#se nuværende working directory</span></span>
<span id="cb1-2"><a href="index.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">list.dirs</span>(<span class="at">path =</span> <span class="st">&quot;.&quot;</span>, <span class="at">recursive =</span> <span class="cn">FALSE</span>) <span class="co">#se mappe indenfor working directory</span></span>
<span id="cb1-3"><a href="index.html#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;~/Documents/&quot;</span>) <span class="co">#sætte en ny working directory (C:/Users/myname/Documents hvis man bruger Windows)</span></span></code></pre></div>
<p>Hvis man bruger Windows, husk at man kan skrive en path på følgende måde:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="index.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#notrun</span></span>
<span id="cb2-2"><a href="index.html#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/myname/Documents&quot;</span>) <span class="co">#enten med /</span></span>
<span id="cb2-3"><a href="index.html#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:</span><span class="sc">\\</span><span class="st">Users</span><span class="sc">\\</span><span class="st">myname</span><span class="sc">\\</span><span class="st">Documents&quot;</span>) <span class="co">#eller med \\</span></span></code></pre></div>
<p><strong>OBS</strong>: jeg bruger Mac, så hvis der er et vigtigt ting at man skal huske hvis man bruger en Windows computer, kan jeg også tilføje det her. Bemærk dog, at de allerfleste ting ved R programmering og tidyverse er ens uanset om man bruger Windows eller Mac.</p>
</div>
<div id="r-pakker" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> R pakker<a href="index.html#r-pakker" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>R pakker er simpelthen en samling af funktioner (eller datasæt i nogle tilfælde), der udvider, hvad er tilgængelige i base-R (den R man få, uden at indlæse en pakke). I R er der mange tusind R pakker (op mod 100,000), der er tilgængelige på <strong>CRAN</strong> (<a href="https://cran.r-project.org/" class="uri">https://cran.r-project.org/</a>). Indenfor det biologiske fag er der også mange flere pakker på <strong>Bioconductor</strong> (<a href="https://www.bioconductor.org/" class="uri">https://www.bioconductor.org/</a>), og i nogle tilfælde kan R pakker også installeres direkte fra <strong>Github</strong>.</p>
<p>I dette kursus arbejder vi rigtig meget med en pakke der hedder <strong>tidyverse</strong>. <strong>tidyverse</strong> er faktisk en samling af otte R pakker, som indlæses på en gang. Inden du indlæse pakken, skal du først sikre dig, at pakken er installeret på systemet ved følgende kommando:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="index.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</span></code></pre></div>
<p>Alle pakker på <strong>CRAN</strong> er installeret på samme måde. Når du faktisk gerne vil bruge en R pakke, skal du først indlæse den ved at bruge <code>library()</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="index.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.0     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.1     ✔ tibble    3.1.8
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<p>Vi kommer til at arbejde med <strong>tidyverse</strong> pakker fra kapitel tre (vi starter med <strong>ggplot2</strong> og så nogle af de andre pakke fra <strong>tidyverse</strong> fra kapitel fire), <strong>så det er en god idé at har tidyverse installeret allerede nu</strong>, når det nogle gange kan tage lidt tid til at installere eller opdatere de mange andre mulige pakker, der <strong>tidyverse</strong> er afhængig af.</p>
<p>Vær opmærksom på, at der nogle gange opstår konflikter når det samme funktionnavn findes i flere pakker - for eksempel, funktionen <code>filter()</code> findes indenfor to forskellige pakker, nemlig <code>dplyr</code> og <code>stats</code>. Når du skriver <code>filter()</code> så ved R ikke, hvilke pakker du mener. I dette tilfælde kan du være gennemskueligt overfor den pakke, du gerne vil bruge ved at skrive <code>dplyr::filter()</code> eller <code>stats:filter()</code> i stedet for bare <code>filter()</code>.</p>
<p>Som sidste kommentar, er det god praksis at indlæse alle pakker, der du benytter sig af, på toppen af din script, så at du hurtigt kan få overblik over, hvilke pakker, der skal indlæses til at få dine koder til at fungere.</p>
</div>
<div id="hvor-kommer-vores-data-fra" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Hvor kommer vores data fra?<a href="index.html#hvor-kommer-vores-data-fra" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>De forskellige datasæt, vi kommer til at arbejde med i kurset stammer fra mange forskellige steder.</p>
<div id="indbyggede-datasæt" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> Indbyggede datasæt<a href="index.html#indbyggede-datasæt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I R er der mange indbygget datasæt som er meget brugbart for at vise koncepter, hvilket gøre dem især populært i undervisningsmateriale. Indbyggede datasæt er ofte tilgængligt indenfor mange pakker, men <code>library(datasets)</code> er den mest brugt (der er også mange indenfor <code>library(ggplot2)</code>. For eksempel, for at indlæse datasættet, der hedder ‘iris’, kan man bruge <code>data()</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="index.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(datasets)</span>
<span id="cb6-2"><a href="index.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span></code></pre></div>
<p>Så er en <em>dataframe</em>, der hedder ‘iris’ tilgængelige som en <em>objekt</em> i <em>workspacen</em> - se den “Environment” fane på højere side i RStudio, eller indtaste <code>ls()</code>, så bør du kunne se et objekt med navnet ‘iris’. Man kan kun arbejde med objekter som er en del af workspacen.</p>
</div>
<div id="importering-af-data-fra-.txt-fil" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> Importering af data fra .txt fil<a href="index.html#importering-af-data-fra-.txt-fil" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Det er meget hyppigt, at man har sin data i formen af en .txt fil eller .xlsx fil på sin computer. Den nemmeste måde at få åbnet en .txt fil er ved at bruge <code>read.table()</code>, som i nedenstående:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="index.html#cb7-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;mydata.txt&quot;</span>) <span class="co">#indlæse data filen mydata.txt som er i working directory</span></span>
<span id="cb7-2"><a href="index.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
<p>Hvis datasættet har kolonner navne, der er skrevet ind i filen, så skal man huske at bruge <code>header=T</code> for at undgå, at den første række i datasættet bliver disse tekste i stedet for virkelige observationer.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="index.html#cb8-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;mydata.txt&quot;</span>,<span class="at">header=</span>T) <span class="co">#indlæse data filen mydata.txt som er i working directory</span></span>
<span id="cb8-2"><a href="index.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code></pre></div>
</div>
<div id="importering-af-data-fra-excel" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> Importering af data fra Excel<a href="index.html#importering-af-data-fra-excel" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Der findes også en hjælpsom pakke, som hedder <strong>readxl</strong>, der kan indlæse Excel-ark direkte ind i R:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="index.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb9-2"><a href="index.html#cb9-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data.xlsx&quot;</span>)</span>
<span id="cb9-3"><a href="index.html#cb9-3" aria-hidden="true" tabindex="-1"></a>data</span></code></pre></div>
</div>
<div id="kaggle" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> Kaggle<a href="index.html#kaggle" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hvis du gerne vil øve dig med statistike analyser (udover nuværende kursus), er Kaggle en fantastisk ressource til at finde forskellige datasæt. I rigtige mange tilfælde kan man også finde analyser some andre har lavet I R (også Python), hvilket kan inspirere jeres egen læring.</p>
<p>Link hvis interesseret: <a href="https://www.kaggle.com/" class="uri">https://www.kaggle.com/</a></p>
</div>
</div>
<div id="beregninger-i-r" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Beregninger i R<a href="index.html#beregninger-i-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Her er nogle helt grundlæggende koncepter når man arbejder med R. Du må selvfølgelige gerne springe sektionen over, hvis du allerede har meget erfaring med base R, men det kan være værd at tjekke, om der noget ting, der lige skal gennemgås. En god tilgang er bare at arbejde gennem problemstillingerne nedenfor, og bruger følgende notater som en reference.</p>
<div id="vectorer" class="section level3 hasAnchor" number="1.6.1">
<h3><span class="header-section-number">1.6.1</span> Vectorer<a href="index.html#vectorer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>I R laver man en vector med <code>c()</code>, hvor man adskiller de forskellige elementer med en komma, som i nedenstående eksempel:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="index.html#cb10-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>) <span class="co">#sæt objektet &#39;a&#39; til at være en vector af tal </span></span>
<span id="cb10-2"><a href="index.html#cb10-2" aria-hidden="true" tabindex="-1"></a>a</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<!-- Man kan også  -->
<!-- ```{r} -->
<!-- a <- 1:5 -->
<!-- ``` -->
<p>Man er ikke begrænset til tal:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="index.html#cb12-1" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;cat&quot;</span>,<span class="st">&quot;mouse&quot;</span>,<span class="st">&quot;horse&quot;</span>,<span class="st">&quot;sheep&quot;</span>,<span class="st">&quot;dog&quot;</span>)</span>
<span id="cb12-2"><a href="index.html#cb12-2" aria-hidden="true" tabindex="-1"></a>c</span></code></pre></div>
<pre><code>## [1] &quot;cat&quot;   &quot;mouse&quot; &quot;horse&quot; &quot;sheep&quot; &quot;dog&quot;</code></pre>
</div>
<div id="datatyper" class="section level3 hasAnchor" number="1.6.2">
<h3><span class="header-section-number">1.6.2</span> datatyper<a href="index.html#datatyper" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Nar vi kommer til at arbejde med visualiseringer og data beardejdning er det vigtigt at have styr på datatyper i datasættet. For eksempel har vectoren <code>c</code> ovenpå typen <code>character</code> (forkortet <code>chr</code>) og ikke <code>numeric</code> (forkortet <code>num</code>):</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="index.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(c)</span>
<span id="cb14-2"><a href="index.html#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] FALSE</span></span>
<span id="cb14-3"><a href="index.html#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">is.character</span>(c)</span>
<span id="cb14-4"><a href="index.html#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] TRUE</span></span></code></pre></div>
<p>Her er en list overfor nogle af de vigtigste datatyper:</p>
<table>
<colgroup>
<col width="33%" />
<col width="41%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Datatype</th>
<th>Navn</th>
<th>Beskrivelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>int</code></td>
<td>integer</td>
<td>kun hel tal <code>c(-1,0,1,2,3)</code></td>
</tr>
<tr class="even">
<td><code>lgl</code></td>
<td>logical</td>
<td><code>TRUE TRUE FALSE TRUE FALSE</code></td>
</tr>
<tr class="odd">
<td><code>chr</code></td>
<td>character</td>
<td><code>c("Bob","Sally","Brian",...)</code></td>
</tr>
<tr class="even">
<td><code>fct</code></td>
<td>factor</td>
<td>bestemte niveauer e.g. <code>Species</code>: <code>c("setosa","versicola")</code></td>
</tr>
<tr class="odd">
<td><code>dbl</code></td>
<td>double</td>
<td>Tal fk. c(<code>4.3902</code>, <code>3.12</code>, <code>4.5</code>)</td>
</tr>
<tr class="even">
<td><code>lst</code></td>
<td>list</td>
<td>blande forskellige data typer og specificere elementer med <code>[[i]]</code> <code>[[1]] [1] c("red","blue")</code> <code>[[2]] [1] TRUE</code> <code>[[3]] [1] c(3,2.3,1.459)</code></td>
</tr>
</tbody>
</table>
<p>En datatype, der bør få særlig opmærksomhed er <code>fct</code> (factor). I følgende vector <code>tea_coffee</code> har vi tekst, men blandt de fem elementer er der kun to bestemte niveauer (nemlig “tea” og “coffee”).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="index.html#cb15-1" aria-hidden="true" tabindex="-1"></a>tea_coffee <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tea&quot;</span>,<span class="st">&quot;tea&quot;</span>,<span class="st">&quot;coffee&quot;</span>,<span class="st">&quot;coffee&quot;</span>,<span class="st">&quot;tea&quot;</span>)</span>
<span id="cb15-2"><a href="index.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(tea_coffee)</span>
<span id="cb15-3"><a href="index.html#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] FALSE</span></span>
<span id="cb15-4"><a href="index.html#cb15-4" aria-hidden="true" tabindex="-1"></a>tea_coffee</span>
<span id="cb15-5"><a href="index.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] &quot;tea&quot;    &quot;tea&quot;    &quot;coffee&quot; &quot;coffee&quot; &quot;tea&quot;</span></span></code></pre></div>
<p>Vi vil derfor gerne fortælle R, at <code>tea_coffee</code> er ikke bare nogle tilfældig tekst men at der er en struktur med, så vi bruger funktionen <code>as.factor</code> for at lave den om til datatypen <code>fct</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="index.html#cb16-1" aria-hidden="true" tabindex="-1"></a>tea_coffee <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(tea_coffee)</span>
<span id="cb16-2"><a href="index.html#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(tea_coffee)</span>
<span id="cb16-3"><a href="index.html#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] TRUE</span></span>
<span id="cb16-4"><a href="index.html#cb16-4" aria-hidden="true" tabindex="-1"></a>tea_coffee</span>
<span id="cb16-5"><a href="index.html#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] tea    tea    coffee coffee tea   </span></span>
<span id="cb16-6"><a href="index.html#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Levels: coffee tea</span></span></code></pre></div>
<p>Den ‘ekstra’ oplysninger man har ved at sige, at en variabel betragtes som factor bliver vigtigt når man arbejder med visualiseringer - for eksempel, hvis vi gerne vil lave et barplot hvor man gerne vil adskille søjlerne efter de to niveauer “tea” og “coffee” (visualiseringer er emnet fra kapitel 3).</p>
</div>
</div>
<div id="dataframes" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Dataframes<a href="index.html#dataframes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><a href="http://www.r-tutor.com/r-introduction/data-frame" class="uri">http://www.r-tutor.com/r-introduction/data-frame</a></p>
<p>Mange af de ting, som vi laver i R tager udgangspunkten i dataframes (eller datarammer).</p>
<!-- height <-  c(140,187,154,132,165) -->
<!-- age <- c(34,31,25,43,29) -->
<!-- score <- c(56,82,48,75,79) -->
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="index.html#cb17-1" aria-hidden="true" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;personID&quot;</span><span class="ot">=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="st">&quot;height&quot;</span><span class="ot">=</span><span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">187</span>,<span class="dv">154</span>,<span class="dv">132</span>,<span class="dv">165</span>), <span class="st">&quot;age&quot;</span><span class="ot">=</span><span class="fu">c</span>(<span class="dv">34</span>,<span class="dv">31</span>,<span class="dv">25</span>,<span class="dv">43</span>,<span class="dv">29</span>))</span>
<span id="cb17-2"><a href="index.html#cb17-2" aria-hidden="true" tabindex="-1"></a>mydf</span></code></pre></div>
<pre><code>##   personID height age
## 1        1    140  34
## 2        2    187  31
## 3        3    154  25
## 4        4    132  43
## 5        5    165  29</code></pre>
<p>Man kan fa adgang til variabler i en dataframe ved at bruge det dollar tegn <code>$</code>. For eksempel giver følgende variablen <code>personID</code> fra dataframen <code>mydf</code>:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="index.html#cb19-1" aria-hidden="true" tabindex="-1"></a>mydf<span class="sc">$</span>personID</span></code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<p>Husk, at vores dataframe, ligesom et matrix (i R: <code>matrix()</code>) har to dimensioner - række og kolonner Forskellen mellem en matrix og en dataramme er, at datarammer kan indeholde mange forskellige data typer (herunder numeriske, faktorer, karakterer osv.), men matrix indeholder kun numeriske data. For eksempel i tilfældet af ovenstående dataframen er alle variabler numeriske, men vi kan godt tilføje en variabel som er ikke-numeriske:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="index.html#cb21-1" aria-hidden="true" tabindex="-1"></a>mydf<span class="sc">$</span>colour <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;green&quot;</span>,<span class="st">&quot;orange&quot;</span>,<span class="st">&quot;purple&quot;</span>) <span class="co">#make new variable which is non-numeric</span></span>
<span id="cb21-2"><a href="index.html#cb21-2" aria-hidden="true" tabindex="-1"></a>mydf</span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 2        2    187  31   blue
## 3        3    154  25  green
## 4        4    132  43 orange
## 5        5    165  29 purple</code></pre>
<p>Nu er <code>mydf</code> er en dataframe, der blander forskellige datatyper, men følgende er en matrix</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="index.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), </span>
<span id="cb23-2"><a href="index.html#cb23-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">nrow=</span><span class="dv">3</span>,</span>
<span id="cb23-3"><a href="index.html#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">ncol=</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    4
## [2,]    2    5
## [3,]    3    6</code></pre>
<p>og kan kun indeholde numeriske data, som kan bruges til at lave matematik operationer (matrix multiplikation osv.). I dette kursus beskæftiger os primært med dataframes (som bliver kaldt for tibbles i <strong>tidyverse</strong>).</p>
<div id="delmængder-af-dataframes" class="section level3 hasAnchor" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Delmængder af dataframes<a href="index.html#delmængder-af-dataframes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Selvom vi kommer til at redefinere hvordan man laver delmængde når vi kommer til at arbejde med pakken <strong>tidyverse</strong>, er det alligevel vigtigt at forstå, hvordan man laver en delmængde i base-R, og det er et område, der ofte skaber forvirring blandt de uerfarne.</p>
<p>Når man vil gerne har en bestemt delmængde af en vector, bruger man firkantet paranteser <code>[ ]</code>. Følgende kode giver mig de første to værdier fra vectoren <code>a</code>:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="index.html#cb25-1" aria-hidden="true" tabindex="-1"></a>a[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 1 2</code></pre>
<p>Bemærk, at mens vectorer har kun en dimension, <strong>har dataframes to dimensioner</strong>. Når man skal lave en delmægde af en dataframe, skal man derfor fortælle R, hvilke række og hvilke kolonner skal være med.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="index.html#cb27-1" aria-hidden="true" tabindex="-1"></a>mydf[række indekser, kolonner indekser]  <span class="co">#not run</span></span></code></pre></div>
<p>For eksempel, hvis vi gerne vil have de første to observationer med, samt kun den anden variabel, skriver man følgende:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="index.html#cb28-1" aria-hidden="true" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">2</span>]  <span class="co">#first two rows (observations), second column (variable) only</span></span></code></pre></div>
<pre><code>## [1] 140 187</code></pre>
<p>Hvis vi vil beholde den første to observationer og samtlige variabler, kan den anden plads være tom:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="index.html#cb30-1" aria-hidden="true" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, ]  <span class="co">#first two rows, all columns</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 2        2    187  31   blue</code></pre>
<p>Jeg kan også angive et variabelnavn direkte:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="index.html#cb32-1" aria-hidden="true" tabindex="-1"></a>mydf[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>,<span class="st">&quot;height&quot;</span>]</span></code></pre></div>
<pre><code>## [1] 140 187</code></pre>
<p>Man kan kigge på en subset af rækkerne i de data ved at</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="index.html#cb34-1" aria-hidden="true" tabindex="-1"></a>mydf[mydf<span class="sc">$</span>height<span class="sc">&gt;=</span><span class="dv">165</span>,] <span class="co">#alle rækker i datarammen med height = 165 eller over</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 2        2    187  31   blue
## 5        5    165  29 purple</code></pre>
<p>Her er en tabel af comparitiver, og jeg gengiver samme tabel når I kommer til at lave delmængde i <strong>tidyverse</strong>:</p>
<table>
<thead>
<tr class="header">
<th>comparitiv</th>
<th>beskrivelse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>&lt;</code></td>
<td>less than</td>
</tr>
<tr class="even">
<td><code>&gt;</code></td>
<td>greater than</td>
</tr>
<tr class="odd">
<td><code>&lt;=</code></td>
<td>less than or equal to</td>
</tr>
<tr class="even">
<td><code>&gt;=</code></td>
<td>greater than or equal to</td>
</tr>
<tr class="odd">
<td><code>==</code></td>
<td>equal to</td>
</tr>
<tr class="even">
<td><code>!=</code></td>
<td>not equal to</td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>and</td>
</tr>
<tr class="even">
<td><code>%in%</code></td>
<td>in</td>
</tr>
<tr class="odd">
<td><code>|</code></td>
<td>or</td>
</tr>
<tr class="even">
<td><code>!</code></td>
<td>not</td>
</tr>
</tbody>
</table>
<p>Jeg mener, at <code>%in%</code> er særlig brugbart og er værd at lære:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="index.html#cb36-1" aria-hidden="true" tabindex="-1"></a>mydf[mydf<span class="sc">$</span>personID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>),] <span class="co">#alle personer med personID 1,3 eller 5 </span></span></code></pre></div>
<pre><code>##   personID height age colour
## 1        1    140  34    red
## 3        3    154  25  green
## 5        5    165  29 purple</code></pre>
<p>Her er et eksempel på, hvordan man bruger udråbstegnet: personer med personID, der ikke er 1,3 eller 5:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="index.html#cb38-1" aria-hidden="true" tabindex="-1"></a>mydf[<span class="sc">!</span>(mydf<span class="sc">$</span>personID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>)),] <span class="co">#alle personer med personID 2 eller 4</span></span></code></pre></div>
<pre><code>##   personID height age colour
## 2        2    187  31   blue
## 4        4    132  43 orange</code></pre>
</div>
</div>
<div id="ifelse" class="section level2 hasAnchor" number="1.8">
<h2><span class="header-section-number">1.8</span> If/else<a href="index.html#ifelse" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If/else kodekonstruktioner giver mulighed for at udføre forskellige handlinger baseret på, om en bestemt betingelse er opfyldt. Her er et eksempel med <code>if</code> med betingelsen <code>number &gt; 0</code>:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="index.html#cb40-1" aria-hidden="true" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="dv">42</span></span>
<span id="cb40-2"><a href="index.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (number <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb40-3"><a href="index.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Number is positive&quot;</span>)</span>
<span id="cb40-4"><a href="index.html#cb40-4" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;Number is positive&quot;</code></pre>
<p>Hvis betingelse er sand udføres den handling indenfor <code>{ }</code>, dvs. “Number is positive” printes.</p>
<p>If/else konstruktioner gør det samme, men hvis betingelsen er falsk, udføres en alternativ handling:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="index.html#cb42-1" aria-hidden="true" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">5</span></span>
<span id="cb42-2"><a href="index.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (number <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb42-3"><a href="index.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Number is positive&quot;</span>)</span>
<span id="cb42-4"><a href="index.html#cb42-4" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb42-5"><a href="index.html#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="st">&quot;Number is not positive&quot;</span>)</span>
<span id="cb42-6"><a href="index.html#cb42-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] &quot;Number is not positive&quot;</code></pre>
<p>Man kan også opnå samme resultat med at bruge <code>ifelse</code>:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="index.html#cb44-1" aria-hidden="true" tabindex="-1"></a>number <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb44-2"><a href="index.html#cb44-2" aria-hidden="true" tabindex="-1"></a>numbers_of_interest <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">7</span>)</span>
<span id="cb44-3"><a href="index.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(<span class="at">test =</span> number <span class="sc">%in%</span> numbers_of_interest, </span>
<span id="cb44-4"><a href="index.html#cb44-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">yes =</span> <span class="st">&quot;Number is interesting&quot;</span>,</span>
<span id="cb44-5"><a href="index.html#cb44-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">no =</span>  <span class="st">&quot;Number is uninteresting&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Number is interesting&quot;</code></pre>
<p>Man behøver ikke at skrive ordene “test”, “yes” og “no” hver gang, såfremt at du bruger samme rækkefølgen som funktionen forventer:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="index.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ifelse</span>(number <span class="sc">%in%</span> numbers_of_interest, </span>
<span id="cb46-2"><a href="index.html#cb46-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">&quot;Number is interesting&quot;</span>,</span>
<span id="cb46-3"><a href="index.html#cb46-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">&quot;Number is uninteresting&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Number is interesting&quot;</code></pre>
</div>
<div id="loops" class="section level2 hasAnchor" number="1.9">
<h2><span class="header-section-number">1.9</span> Loops<a href="index.html#loops" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>I base-R kan man laver simpel loops med følgende konstruktion:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="index.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>) {</span>
<span id="cb48-2"><a href="index.html#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(i)</span>
<span id="cb48-3"><a href="index.html#cb48-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 5</code></pre>
<p>Loops bliver et stort emne senere i kurset (emne 8/9).</p>
</div>
<div id="descriptive-statistics" class="section level2 hasAnchor" number="1.10">
<h2><span class="header-section-number">1.10</span> Descriptive statistics<a href="index.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="simulere-data-fra-den-normale-fordeling" class="section level3 hasAnchor" number="1.10.1">
<h3><span class="header-section-number">1.10.1</span> Simulere data fra den normale fordeling<a href="index.html#simulere-data-fra-den-normale-fordeling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Hvis du har bruge for at vide mere om den normale fordeling: <a href="http://www.r-tutor.com/elementary-statistics/probability-distributions/normal-distribution" class="uri">http://www.r-tutor.com/elementary-statistics/probability-distributions/normal-distribution</a></p>
<p>Man kan nemt lave sin egne ‘fake’ data ved at simulere det fra en fordeling, der typisk er normalfordelingen, da den er den mest almindelige fordeling i den virkelige verden (husk den klassiske klokkeform). I R kan funktionen rnorm bruges til at simulere data. Først angiver man antallet af observationer, og derefter den gennemsnitlige værdi og standardafvigelsen (sd), som er de to nødvendige parametre for at beskrive en normalfordeling.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="index.html#cb50-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>,<span class="at">mean=</span><span class="dv">0</span>,<span class="at">sd=</span><span class="dv">1</span>) <span class="co">#standard normal distribution</span></span>
<span id="cb50-2"><a href="index.html#cb50-2" aria-hidden="true" tabindex="-1"></a>x <span class="co">#så har vi 25 værdier fra en normal distribution med mean=0 og standard deviation=1.</span></span></code></pre></div>
<pre><code>##  [1]  0.7913762 -0.3103239 -1.9522838 -0.2464443  0.3428662 -0.6234515
##  [7]  0.8118684  0.6668080  1.4637336  0.2155633  0.3576463  0.5224231
## [13]  0.9436376  3.3402680  0.4221501  0.6426034 -2.1670643 -1.1889863
## [19] -1.0223551  0.2775816 -0.3256193 -1.0184257 -1.0540547 -0.5261362
## [25]  2.4555805</code></pre>
<p>I stedet for at kigge på alle værdier på én gang, vil vi måske hellere kigge kun på de første (eller sidste) værdier:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="index.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(x) <span class="co">#første 6</span></span>
<span id="cb52-2"><a href="index.html#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="do">## [1]  0.7913762 -0.3103239 -1.9522838 -0.2464443  0.3428662 -0.6234515</span></span>
<span id="cb52-3"><a href="index.html#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(x) <span class="co">#sidste 6</span></span>
<span id="cb52-4"><a href="index.html#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [1]  0.2775816 -0.3256193 -1.0184257 -1.0540547 -0.5261362  2.4555805</span></span>
<span id="cb52-5"><a href="index.html#cb52-5" aria-hidden="true" tabindex="-1"></a>x[<span class="dv">1</span>] <span class="co">#første værdi</span></span>
<span id="cb52-6"><a href="index.html#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 0.7913762</span></span>
<span id="cb52-7"><a href="index.html#cb52-7" aria-hidden="true" tabindex="-1"></a>x[<span class="fu">length</span>(x)] <span class="co">#sidste data point</span></span>
<span id="cb52-8"><a href="index.html#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 2.45558</span></span></code></pre></div>
<p>Bemærk, at i modsætning til Python og mange andre programmeringssprog, bruger R en 1-baseret indeksering. Det betyder, at den første værdi er x[1] og ikke x[0] som i Python.</p>
</div>
<div id="measures-of-central-tendency" class="section level3 hasAnchor" number="1.10.2">
<h3><span class="header-section-number">1.10.2</span> Measures of central tendency<a href="index.html#measures-of-central-tendency" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table>
<colgroup>
<col width="50%" />
<col width="50%" />
</colgroup>
<thead>
<tr class="header">
<th>function</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>mean()</code></td>
<td>mean <span class="math inline">\(\bar{x}_{i} = \frac{1}{n}\sum_{i=1}^{n} x_{i}\)</span></td>
</tr>
<tr class="even">
<td><code>median()</code></td>
<td>median value</td>
</tr>
<tr class="odd">
<td><code>max()</code></td>
<td>maximum value</td>
</tr>
<tr class="even">
<td><code>min()</code></td>
<td>minimum value</td>
</tr>
<tr class="odd">
<td><code>var()</code></td>
<td>variance <span class="math inline">\(s^2 = \frac{1}{n-1}\sum_{i=1}^{n} (x_{i} - \bar{x}_{i})^2\)</span></td>
</tr>
<tr class="even">
<td><code>sd()</code></td>
<td>standard deviation <span class="math inline">\(s\)</span></td>
</tr>
</tbody>
</table>
<p>Lad os afprøve dem på vores simulerede data:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="index.html#cb53-1" aria-hidden="true" tabindex="-1"></a>my_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb53-2"><a href="index.html#cb53-2" aria-hidden="true" tabindex="-1"></a>my_median <span class="ot">&lt;-</span> <span class="fu">median</span>(x)</span>
<span id="cb53-3"><a href="index.html#cb53-3" aria-hidden="true" tabindex="-1"></a>my_max <span class="ot">&lt;-</span> <span class="fu">max</span>(x)</span>
<span id="cb53-4"><a href="index.html#cb53-4" aria-hidden="true" tabindex="-1"></a>my_min <span class="ot">&lt;-</span> <span class="fu">min</span>(x)</span>
<span id="cb53-5"><a href="index.html#cb53-5" aria-hidden="true" tabindex="-1"></a>my_var <span class="ot">&lt;-</span> <span class="fu">var</span>(x)</span>
<span id="cb53-6"><a href="index.html#cb53-6" aria-hidden="true" tabindex="-1"></a>my_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(x)</span>
<span id="cb53-7"><a href="index.html#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(my_mean,my_median,my_max,my_min,my_var,my_sd) <span class="co">#print results</span></span></code></pre></div>
<pre><code>## [1]  0.1127584  0.2775816  3.3402680 -2.1670643  1.5378646  1.2401067</code></pre>
<p>Man kan også lave et summary af dataen, som består af mange af de statistiker navnt ovenpå:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="index.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -2.1671 -0.6235  0.2776  0.1128  0.6668  3.3403</code></pre>
</div>
<div id="tapply" class="section level3 hasAnchor" number="1.10.3">
<h3><span class="header-section-number">1.10.3</span> <code>tapply()</code><a href="index.html#tapply" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>tapply()</code> er en meget nyttig funktion i R, som kan bruges til at anvende en funktion på en gruppe af data baseret på værdier i en anden vektor. Funktionen tager tre hovedargumenter: den vektor, som vi ønsker at anvende funktionen på, den vektor, som bruges til at gruppere dataene, og funktionen, som vi ønsker at anvende på hver gruppe. <code>tapply()</code> vil derefter opdele dataene i grupper baseret på den anden vektor og anvende funktionen på hver gruppe.</p>
<p>Resultatet af <code>tapply()</code> vil være en vektor, som indeholder resultaterne af funktionen anvendt på hver gruppe af data. For eksempel:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="index.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb57-2"><a href="index.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(iris<span class="sc">$</span>Sepal.Length,iris<span class="sc">$</span>Species,mean) <span class="co"># ovenstående i kun en linje</span></span></code></pre></div>
<pre><code>##     setosa versicolor  virginica 
##      5.006      5.936      6.588</code></pre>
<p>Her tager vi en vektor ved navn Sepal.Length, opdeler den efter Species og beregner gennemsnittet ved hjælp af funktionen mean for hver af de tre arter i Species (setosa, versicolor og virginica). Alternativt kunne man have beregnet gennemsnittet for hver af de tre Species separat (en tilgang, der ikke skalerer godt!):</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="index.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species setosa</span></span>
<span id="cb59-2"><a href="index.html#cb59-2" aria-hidden="true" tabindex="-1"></a>mean_setosa <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;setosa&quot;</span>])</span>
<span id="cb59-3"><a href="index.html#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="index.html#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species versicolor</span></span>
<span id="cb59-5"><a href="index.html#cb59-5" aria-hidden="true" tabindex="-1"></a>mean_versi <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;versicolor&quot;</span>]) </span>
<span id="cb59-6"><a href="index.html#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="index.html#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># gennemsnit Sepal Length for Species virginica</span></span>
<span id="cb59-8"><a href="index.html#cb59-8" aria-hidden="true" tabindex="-1"></a>mean_virgin <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Sepal.Length[iris<span class="sc">$</span>Species<span class="sc">==</span><span class="st">&quot;virginica&quot;</span>])</span>
<span id="cb59-9"><a href="index.html#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="index.html#cb59-10" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(mean_setosa,mean_versi,mean_virgin)</span></code></pre></div>
<pre><code>## [1] 5.006 5.936 6.588</code></pre>
<p>Det er også værd at ved koncepten, fordi vi kommer til lære en lignende koncept i <strong>tidyverse</strong> (med <code>group_by</code> og <code>summarise</code>).</p>
</div>
</div>
<div id="statistike-tester" class="section level2 hasAnchor" number="1.11">
<h2><span class="header-section-number">1.11</span> Statistike tester<a href="index.html#statistike-tester" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<!-- Her er nogle koncepter der jeg forventer, at I har mere eller mindre set før begyndelsen af dette kursus. Jeg forventer ikke at I huske alle detaijler, derfor gå jeg hurtige igennem både koncepter og hvordan man bruger dem i R (vigtigt) undervejs, på de tidspunkter vi støder ind i dem. Hvis der er dog noget, at du som den enkelte studerende slet ikke har set før, anbefelder jeg, at du tjekker på Google hvad det gå ud på. -->
<!-- Jeg går ud fra at du har et kendskab til de meste grundlæggende statistiske koncepter såsom p-værdi, signifikansniveau, null/alternativ hypotese, 1- eller 2- sidet test og så videre. Se gerne jeres notater fra tidligere kurser (eller læse online) hvis du har bruge for at gennemgå de koncepter. -->
<p>Her er en oversigt over nogle af de mest grundlæggende tests, som man kan udføre på data i R. Det kan være nyttigt som en reference senere hen, hvis det er nødvendigt. Jeg vil ikke gå i dybden med teorien bag disse tests (da det antages, at du har lært det tidligere), men jeg forventer, at du er i stand til at anvende dem korrekt i R og fortolke resultaterne. Hvis du ikke er bekendt med nogle af disse tests, vil der være masser af muligheder for at øve dig i statistik gennem kurset.</p>
<p>t-test: Bruges til at sammenligne to grupper og afgøre, om forskellen mellem deres gennemsnitlige værdier er statistisk signifikant.</p>
<p>ANOVA: Bruges til at sammenligne mere end to grupper og afgøre, om der er statistisk signifikant forskel mellem mindst to af grupperne.</p>
<p>Korrelationsanalyse: Bruges til at afgøre, om der er en statistisk signifikant sammenhæng mellem to variabler.</p>
<p>Regressionsanalyse: Bruges til at afgøre, om der er en statistisk signifikant sammenhæng mellem en uafhængig variabel og en afhængig variabel og at forudsige værdien af den afhængige variabel baseret på værdien af den uafhængige variabel.</p>
<p>Chi-square test: Bruges til at afgøre, om der er en statistisk signifikant forskel mellem observerede og forventede værdier for kategoriske variabler.</p>
<div id="p-værdien" class="section level3 hasAnchor" number="1.11.1">
<h3><span class="header-section-number">1.11.1</span> P-værdien<a href="index.html#p-værdien" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Først og fremmest er det vigtigt at kunne huske p-værdi både i forhold til definitionen og i forhold til hvordan det fortolkes.</p>
<p>P-værdien er sandsynligheden for at observere et resultat lige så ekstremt eller mere ekstremt end det observerede, givet at null-hypotesen er sand. Null-hypotesen er en antagelse om, at der ikke er nogen signifikant forskel mellem grupper eller variabler i det dataset, som der arbejdes med.</p>
<p>Hvis p-værdien er mindre end det valgte signifikansniveau (typisk 0,05), så betyder det, at det observerede resultat er usandsynligt at opstå ved ren tilfældighed, og null-hypotesen forkastes til fordel for den alternative hypotese om, at der er en signifikant forskel mellem grupper eller variabler i datasættet.</p>
</div>
<div id="korrelation" class="section level3 hasAnchor" number="1.11.2">
<h3><span class="header-section-number">1.11.2</span> Korrelation<a href="index.html#korrelation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Korrelation måler styrken og retningen af den lineære sammenhæng mellem to kontinuerte variabler, som begge er normalfordelte:</p>
<ul>
<li><span class="math inline">\(&gt;0\)</span> betyder, at der er en positiv sammenhæng</li>
<li><span class="math inline">\(&lt;0\)</span> betyder, at der er en negativ sammenhæng</li>
<li><span class="math inline">\(=0\)</span> betyder, at der er ingen sammenhængen mellem de to variabler</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="index.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cars)</span>
<span id="cb61-2"><a href="index.html#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(cars<span class="sc">$</span>speed, cars<span class="sc">$</span>dist) </span></code></pre></div>
<pre><code>## [1] 0.8068949</code></pre>
<p>Husk dog, at “Correlation does not equal causation” - dvs. at korrelation er bare en sammenhæng og ikke nødvendigvis angiver en årsagssammenhæng mellem de to variable.</p>
<p>Funktionen <code>cor.test()</code> kan bruges til at teste, om korrelationen mellem to variable er statistisk signifikant. Null-hypotesen antager, at der ikke er nogen korrelation mellem de to variable i den population, som datasættet repræsenterer.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="index.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(cars<span class="sc">$</span>speed, cars<span class="sc">$</span>dist) </span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  cars$speed and cars$dist
## t = 9.464, df = 48, p-value = 1.49e-12
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6816422 0.8862036
## sample estimates:
##       cor 
## 0.8068949</code></pre>
<p>Så kan man se, at p-værdien er 0, der er under 0.05. Derfor konkluderer man, at der er en signifikant sammenhæng mellem de to variabler.</p>
</div>
<div id="test-for-uafhængighed-chi-sq-test" class="section level3 hasAnchor" number="1.11.3">
<h3><span class="header-section-number">1.11.3</span> Test for uafhængighed (chi-sq test)<a href="index.html#test-for-uafhængighed-chi-sq-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En chi-squared test kan bruges til at undersøge, om der er en statistisk signifikant sammenhæng mellem antallet af observationer i to eller flere forskellige kategorier. For eksempel kan man teste for sammenhængen mellem antallet af kopier af en genvariant og to forskellige farver på blomster i en bestemt planteart.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">0</th>
<th align="center">1</th>
<th align="center">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>red</td>
<td align="center">29</td>
<td align="center">31</td>
<td align="center">16</td>
</tr>
<tr class="even">
<td>pink</td>
<td align="center">11</td>
<td align="center">16</td>
<td align="center">24</td>
</tr>
</tbody>
</table>
<p>Vi vil gerne vide, om phenotype er afhængig af genotype:</p>
<ul>
<li><span class="math inline">\(H_{0}:\)</span> antal gen copi og phenotype er uafhængie af hinanden VS</li>
<li><span class="math inline">\(H_{1}:\)</span> antal gen copi og phenotype er afhængie af hinanden</li>
</ul>
<p>Testen går ud på, at man beregner forventede værdier under nulhypotesen om, at der ikke er nogen sammenhæng mellem de to kategorier, og sammenligner disse forventede værdier med observerede værdier. Man laver testen i R ved at benytte funktionen <code>chisq.test()</code>:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="index.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(dat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  dat
## X-squared = 9.9516, df = 2, p-value = 0.006903</code></pre>
<p>Her er p-værdien = 0.006903 &lt; 0.05, så vi forkaster nulhypotesen og konkluderer, at der er en signifikant sammenhæng mellem de to variabler. Ud fra rådatasættet kan man også observere, at der er flere røde blomster uden nogen kopi af genet sammenlignet med røde blomster med to kopier af genet, mens det modsatte er tilfældet for de lyserøde blomster.</p>
</div>
<div id="sample-t-test" class="section level3 hasAnchor" number="1.11.4">
<h3><span class="header-section-number">1.11.4</span> 1 sample t-test<a href="index.html#sample-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For at vise en 1-sample t-test, simulerer jeg nogle data fra en normalfordeling med middelværdi på 3 ved hjælp af rnorm()-funktionen:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="index.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">290223</span>) <span class="co"># bare for at få den samme resultat hver gang</span></span>
<span id="cb67-2"><a href="index.html#cb67-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="at">mean =</span> <span class="dv">3</span>,<span class="at">sd =</span> <span class="dv">1</span>)</span></code></pre></div>
<p>Forestil dig, at du ikke helt stoler på funktionen <code>rnorm()</code> og ønsker at teste, om <code>x</code> stammer fra en normalfordeling med en middelværdi på 3. Nulhypotesen og den alternative hypotese (to-sidet test) er derfor:</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu = 3\)</span>, VS</li>
<li><span class="math inline">\(H_{1}: \mu \neq 3\)</span></li>
</ul>
<p>For at lave testen i R, bruger man funktionen <code>t.test()</code> og angiver <code>mu = 3</code> for at reflektere vores hypoteser:</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="index.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x,<span class="at">mu =</span> <span class="dv">3</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  x
## t = -1.1448, df = 9, p-value = 0.2818
## alternative hypothesis: true mean is not equal to 3
## 95 percent confidence interval:
##  2.169968 3.272231
## sample estimates:
## mean of x 
##  2.721099</code></pre>
<p>Fra resultatet kan man se, at p-værdien er estimeret til 0.2818, og da den er &gt; 0.05 kan vi ikke forkaste nulhypotesen, og vi konkluderer derfor, at middelværdien af x ikke adskiller sig signifikant fra 3.</p>
<p><strong>Bemærkning</strong>: da vi simulerede vores data fra en normal fordeling med et gennemsnit på tre, vidste vi i forvejen at det korrekte svar er, at beholde nullhypotesen. Havde vi forkastet nullhypotesen, havde vi lavet en <strong>type I fejl</strong> - det vil sige, at vi forkaster nullhypotesen når det faktisk er sandt.</p>
</div>
<div id="sample-t-test-1" class="section level3 hasAnchor" number="1.11.5">
<h3><span class="header-section-number">1.11.5</span> 2-sample t-test<a href="index.html#sample-t-test-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Undersøger om der er en forskel i de gennemsnitlige værdier mellem to grupper - kan de to grupper betragtes til at stammer fra den samme normale fordeling? Hypoteserne er således (to-sidet):</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu_{1} = \mu_{2}\)</span>, VS</li>
<li><span class="math inline">\(H_{1}: \mu_{1} \neq \mu_{2}\)</span></li>
</ul>
<p>I følgende kode simulere jeg to stikprøver, der kommer fra en normal fordeling med forskellige gennemsnitte og bruger funktionen <code>t.test</code>. Man kan angive at de to stikprøver har samme variance ved at skrive <code>var.equal = T</code> indenfor funktionen <code>t.test</code>:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="index.html#cb70-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb70-2"><a href="index.html#cb70-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">1</span>)</span>
<span id="cb70-3"><a href="index.html#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="index.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x,y,<span class="at">var.equal =</span> T)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  x and y
## t = -5.4258, df = 18, p-value = 3.729e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.700858 -1.193081
## sample estimates:
## mean of x mean of y 
##  2.783056  4.730025</code></pre>
<p>Hvis man til gengæld ikke kan antage, at variansen er den samme i de to grupper:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="index.html#cb72-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb72-2"><a href="index.html#cb72-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">5</span>,<span class="dv">3</span>) <span class="co">#større variance</span></span>
<span id="cb72-3"><a href="index.html#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="index.html#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(x,y,<span class="at">var.equal =</span> F) <span class="co">#var.equal=F er &#39;default&#39; så man behøver ikke at specifere</span></span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  x and y
## t = -2.0238, df = 11.77, p-value = 0.0663
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -3.9077927  0.1483728
## sample estimates:
## mean of x mean of y 
##  2.757436  4.637146</code></pre>
<p>Bemærk at hvis man kan antage at variancen er den samme, så har man mere <strong>power</strong> (kræft) til at kalde en virkelig forskel for signifikant.</p>
</div>
<div id="paired-t-test" class="section level3 hasAnchor" number="1.11.6">
<h3><span class="header-section-number">1.11.6</span> Paired t-test<a href="index.html#paired-t-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En paired t-test bruges når man for eksempel har målinger for den samme sæt personer i hver stikprøve, og man gerne vil teste om forskellen i værdier mellem de to stikprøver er signifikant. For eksempel hvis vi har “before” og “after” målinger for den samme 10 individer:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="index.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">320</span>)</span>
<span id="cb74-2"><a href="index.html#cb74-2" aria-hidden="true" tabindex="-1"></a>before <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">3</span>,<span class="dv">1</span>)</span>
<span id="cb74-3"><a href="index.html#cb74-3" aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">6</span>,<span class="dv">2</span>)</span>
<span id="cb74-4"><a href="index.html#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="index.html#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(before,after,<span class="at">paired=</span>T) <span class="co">#specificy paired data</span></span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  before and after
## t = -9.3296, df = 9, p-value = 6.356e-06
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -5.415186 -3.301613
## sample estimates:
## mean difference 
##       -4.358399</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="index.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(before<span class="sc">-</span>after,<span class="at">mu=</span><span class="dv">0</span>) <span class="co">#exactly the same result</span></span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  before - after
## t = -9.3296, df = 9, p-value = 6.356e-06
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -5.415186 -3.301613
## sample estimates:
## mean of x 
## -4.358399</code></pre>
</div>
<div id="anova-variansanalyse" class="section level3 hasAnchor" number="1.11.7">
<h3><span class="header-section-number">1.11.7</span> ANOVA (variansanalyse)<a href="index.html#anova-variansanalyse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Har man flere grupper i stedet for to, kan man bruge ANOVA (analysis of variance eller variansanalyse). For en kategorisk variabel med <span class="math inline">\(k\)</span> grupper, er nul/alternativhypotesen:</p>
<ul>
<li><span class="math inline">\(H_{0}: \mu_{1} = \mu_{2} = \ldots = \mu_{k}\)</span></li>
<li><span class="math inline">\(H_{1}:\)</span> ikke alle middelværdier er enes</li>
</ul>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="index.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#simulere data til 3 forskellige grupper fra den normale fordeling med standard afvigelse af 3</span></span>
<span id="cb78-2"><a href="index.html#cb78-2" aria-hidden="true" tabindex="-1"></a>group1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>,<span class="dv">10</span>,<span class="dv">3</span>)</span>
<span id="cb78-3"><a href="index.html#cb78-3" aria-hidden="true" tabindex="-1"></a>group2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">55</span>,<span class="dv">10</span>,<span class="dv">3</span>)</span>
<span id="cb78-4"><a href="index.html#cb78-4" aria-hidden="true" tabindex="-1"></a>group3 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">48</span>,<span class="dv">5</span>,<span class="dv">3</span>)</span>
<span id="cb78-5"><a href="index.html#cb78-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-6"><a href="index.html#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="co">#data må være i en dataramme, med den ene kolon = vores værdier, og den anden kolon = grupper</span></span>
<span id="cb78-7"><a href="index.html#cb78-7" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(group1,group2,group3)</span>
<span id="cb78-8"><a href="index.html#cb78-8" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;G1&quot;</span>,<span class="dv">50</span>),<span class="fu">rep</span>(<span class="st">&quot;G2&quot;</span>,<span class="dv">55</span>),<span class="fu">rep</span>(<span class="st">&quot;G3&quot;</span>,<span class="dv">48</span>))</span>
<span id="cb78-9"><a href="index.html#cb78-9" aria-hidden="true" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;group&quot;</span><span class="ot">=</span>x,<span class="st">&quot;value&quot;</span><span class="ot">=</span>y)</span></code></pre></div>
<p>For at udføre testen kan man bruge funktionen lm(), som står for “linear model” og kan bruges til at opbygge forskellige modeller. Her angiver vi en model, hvor hver gruppe (<code>G1</code>, <code>G2</code> og <code>G3</code> fra variablen <code>x</code>) har sin egen middelværdi (variablen value), hvilket er modellen under alternativhypotesen:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="index.html#cb79-1" aria-hidden="true" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(value<span class="sc">~</span>group,<span class="at">data=</span>mydf) <span class="co">#H1 model</span></span></code></pre></div>
<p>Under nulhypotesen har alle grupper den samme middelværdi, og derfor behøver vi ikke at inkludere variablen <code>group</code> i modellen. Vi angiver situationen i modellen ved at skrive 1, som betyder, at forventede værdier for den afhængige variabel <code>value</code> blot er dens middelværdi:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="index.html#cb80-1" aria-hidden="true" tabindex="-1"></a>mylm_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(value<span class="sc">~</span><span class="dv">1</span>,<span class="at">data=</span>mydf) <span class="co">#H0 model</span></span></code></pre></div>
<p>For at sammenligne de to modeller benytter vi funktionen <code>anova()</code> (efter analysis of variance):</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="index.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mylm_null,mylm)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: value ~ 1
## Model 2: value ~ group
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    152 2215.4                                  
## 2    150 1509.9  2    705.55 35.047 3.245e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>P-værdien er (&lt;0.05), så nulhypotesen er forkastet til fordel af alternativhypotesen, altså modellen, hvor hver gruppe har sin egen middelværdi. Bemærk at det er til trods af, at to af de tre grupper kommer fra en normal fordeling med præcis de samme middelværdier (det er nok, at den trejde gruppe har en ænderledes middelværdi).</p>
<!-- * Grupper må være normale fordelt -->
<!-- * Variancen må være de samme i alle grupper -->
</div>
<div id="lineær-regression" class="section level3 hasAnchor" number="1.11.8">
<h3><span class="header-section-number">1.11.8</span> Lineær regression<a href="index.html#lineær-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><em>OBS: se også video i forbindelse med Rmarkdown (næste emne), hvor jeg gennemgå lineær regression med R</em></p>
<p>Formål: måler (en retningsbestemt) relation mellem to kontinuerte variabler. I simpel lineær regression svarer det til, at man gerne vil finde den rette linje gennem punkterne, der bedste beskriver relationen.</p>
<p>Eksempel - datasættet <code>mtcars</code>, response (afgængig) variabel er <code>mpg</code> og predictor (uafhængig) variabel er <code>wt</code>.</p>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-50-1.png" width="480" /></p>
<p>Man skriver relationen i R som <code>mpg ~ wt</code> og benytter <code>lm()</code>(<code>lm(mpg~wt,data=mtcars)</code>):</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="index.html#cb83-1" aria-hidden="true" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data=</span>mtcars)  <span class="co"># build linear regression model</span></span>
<span id="cb83-2"><a href="index.html#cb83-2" aria-hidden="true" tabindex="-1"></a>mylm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Coefficients:
## (Intercept)           wt  
##      37.285       -5.344</code></pre>
<p>Vores “Coefficients” beskriver den bedste rette linje:</p>
<ul>
<li>Skæringen (intercept): 37.285</li>
<li>Hældningskoefficient (slope): -5.344</li>
</ul>
<p>Det betyder, at hvis vægten <code>wt</code> af en bil stiger med 1, så stiger <code>mpg</code> ved -5.344 (det vil sige at <code>mpg</code> reduceres med 5.344).</p>
</div>
<div id="r-squared-coefficient-of-determination" class="section level3 hasAnchor" number="1.11.9">
<h3><span class="header-section-number">1.11.9</span> R-squared coefficient of determination<a href="index.html#r-squared-coefficient-of-determination" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Den <span class="math inline">\(R^2\)</span> eller “forklaringsgraden” (coefficeint of determination) har til formål at forklare, hvor godt vores lineær model passer til de data. For eksempel hvor meget af variansen i <code>mpg</code> forklares af variablen <code>wt</code>?</p>
<ul>
<li>Hvis det er tæt på 1 - så er der en meget tæt relation (hvis man kender vægten, så vide man også <code>mpg</code> med stor sikkerhed)</li>
<li>Hvis det er tæt på 0 - så er relationen svag - høj sandsynlighed for, at der er andre variabler der bedre kan forklare variansen i <code>mpg</code>.</li>
</ul>
<p>I ovenstående model, kan man se den <span class="math inline">\(R^2\)</span> værdi med <code>summary(mylm)</code>.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="index.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5432 -2.3647 -0.1252  1.4096  6.8727 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
## wt           -5.3445     0.5591  -9.559 1.29e-10 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.046 on 30 degrees of freedom
## Multiple R-squared:  0.7528, Adjusted R-squared:  0.7446 
## F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
<p>Det fortæller os, at <span class="math inline">\(R^2\)</span> = 0.7528.</p>
</div>
<div id="antagelser---lineær-regression" class="section level3 hasAnchor" number="1.11.10">
<h3><span class="header-section-number">1.11.10</span> Antagelser - lineær regression<a href="index.html#antagelser---lineær-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Normalfordelte residualer</li>
<li>Residualer har samme spredning (varianshomogenitet)</li>
<li>Uafhængighed</li>
<li>Fit er linæer</li>
</ul>
<p>Koden <code>plot(mylm,which=c(1))</code> angiver residualer vs predikterede (fitted) værdier - de skal være tilfældigt fordelt over plottet og prikkernes varians skal være nogenlunde konstant langt x-aksen (det giver, at den røde linje er flade).</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="index.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mylm,<span class="at">which=</span><span class="fu">c</span>(<span class="dv">1</span>))</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-53-1.png" width="480" /></p>
<p>Med koden <code>plot(mylm,which=c(2))</code> kan man tjekke antagelsen på en normal fordeling. Punkterne skal være nogenlunde tæt på den diagonale linje.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="index.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mylm,<span class="at">which=</span><span class="fu">c</span>(<span class="dv">2</span>))</span></code></pre></div>
<p><img src="visualisering_22_files/figure-html/unnamed-chunk-54-1.png" width="480" /></p>
</div>
<div id="multiple-lineær-regression" class="section level3 hasAnchor" number="1.11.11">
<h3><span class="header-section-number">1.11.11</span> Multiple lineær regression<a href="index.html#multiple-lineær-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Her kan man tilføje flere variabler i vores model formel.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="index.html#cb89-1" aria-hidden="true" tabindex="-1"></a>mylm_disp <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> disp, <span class="at">data=</span>mtcars) <span class="co"># build linear regression model</span></span>
<span id="cb89-2"><a href="index.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylm_disp)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.4087 -2.3243 -0.7683  1.7721  6.3484 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 34.96055    2.16454  16.151 4.91e-16 ***
## wt          -3.35082    1.16413  -2.878  0.00743 ** 
## disp        -0.01773    0.00919  -1.929  0.06362 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.917 on 29 degrees of freedom
## Multiple R-squared:  0.7809, Adjusted R-squared:  0.7658 
## F-statistic: 51.69 on 2 and 29 DF,  p-value: 2.744e-10</code></pre>
<p>Her kan man se, at med tilføjelsen af variablen <code>disp</code>, er <span class="math inline">\(R^2\)</span> steget til 0.7809. Bemærk, at jo flere variabler man tilføjer til modellen, jo større bliver <span class="math inline">\(R^2\)</span>-værdien. Den adjusted <span class="math inline">\(R^2\)</span> værdi er lavere fordi den prøver at tage højde for kompleksiteten af modellen (hvor mange parametre der er).</p>
<p>Variablen <code>disp</code> er faktisk ikke selv signifikant når der er taget højde for variablen <code>wt</code> (p-værdien 0.0636 - tjek, at du selv kan finde værdien i resultatet).</p>
<p>Hvis en af de uafhængige variabler er kategorisk bruger man funktionen <code>anova</code> til at teste den overordnet effekt af den variabel. For eksempel har variablen <code>cyl</code> 3 mulige værdier (niveauer) - 4, 6 og 8. Vi kan inddrage variablen i vores model: –&gt;</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="index.html#cb91-1" aria-hidden="true" tabindex="-1"></a>mylm_cyl <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> <span class="fu">factor</span>(cyl), <span class="at">data=</span>mtcars) <span class="co"># build linear regression model</span></span>
<span id="cb91-2"><a href="index.html#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylm_cyl)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ wt + factor(cyl), data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5890 -1.2357 -0.5159  1.3845  5.7915 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   33.9908     1.8878  18.006  &lt; 2e-16 ***
## wt            -3.2056     0.7539  -4.252 0.000213 ***
## factor(cyl)6  -4.2556     1.3861  -3.070 0.004718 ** 
## factor(cyl)8  -6.0709     1.6523  -3.674 0.000999 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.557 on 28 degrees of freedom
## Multiple R-squared:  0.8374, Adjusted R-squared:   0.82 
## F-statistic: 48.08 on 3 and 28 DF,  p-value: 3.594e-11</code></pre>
<!-- Der er faktisk tre rette linjer her - en for hvert niveau af `cyl`, og de har samme hældning med forskellige skæringspunkter. -->
<!-- * Hvis `cyl = 4`: mpg $= 33.99 - 3.21$wt -->
<!-- * Hvis `cyl = 6`: mpg $= 33.99 - 3.21$wt $-4.26$ -->
<!-- * Hvis `cyl = 8`: mpg $= 33.99 - 3.21$wt $-6.07$ -->
<p>Man kan ikke se den overordnet effekt af <code>cyl</code> fra den ovenstående <code>summary</code> men man kan teste den med <code>anova</code>:</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="index.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(mylm,mylm_cyl)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: mpg ~ wt
## Model 2: mpg ~ wt + factor(cyl)
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     30 278.32                                
## 2     28 183.06  2    95.263 7.2856 0.002835 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Så kan man se, at <code>cyl</code> er signifikant.</p>
</div>
</div>
<div id="problemstillinger" class="section level2 hasAnchor" number="1.12">
<h2><span class="header-section-number">1.12</span> Problemstillinger<a href="index.html#problemstillinger" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Husk quizzen på Absalon, og lav gerne nogle øvelser for at øve dine færdigheder i R:</p>
<ul>
<li>Øvelse 2-8 er meget grundlæggende og i godt kan springes over, hvis man er nogenlunde fortrolig med base-R.</li>
<li>Jeg vil anbefale øvelse 9-15 til alle som en god måde at teste deres viden på.</li>
<li>Øvelse 16-20 fokuserer på andre statistiske test i R. Vi vil komme tilbage til regression flere gange i kurset, så det vil være en god idé at have kendskab til funktionen <code>lm()</code> til at opbygge modeller i ANOVA / simpel lineær regression (se også videoen og problemstillingerne til det næste emne R Markdown).</li>
</ul>
<div id="quiz---basics" class="section level3 hasAnchor" number="1.12.1">
<h3><span class="header-section-number">1.12.1</span> Quiz - Basics<a href="index.html#quiz---basics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>1)</strong> Lav quiz i Absalon, der hedder “Quiz - Basics”.</p>
</div>
<div id="grundlæggende-r" class="section level3 hasAnchor" number="1.12.2">
<h3><span class="header-section-number">1.12.2</span> Grundlæggende R<a href="index.html#grundlæggende-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>2)</strong> (<strong>helt baserende viden</strong>) Åbn en ny fil i RStudio ved at klikke på “File” &gt; “New File” &gt; “R Script”. Kør følgende kode en linje ad gangen og tjek, om du forstår outputtet.</p>
<p>Husk, at den nemmeste måde at køre kode på er ved at trykke på CMD+ENTER (Mac) eller WIN-KEY+ENTER (Windows).</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="index.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">+</span><span class="dv">2</span></span>
<span id="cb95-2"><a href="index.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="dv">2</span></span>
<span id="cb95-3"><a href="index.html#cb95-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb95-4"><a href="index.html#cb95-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> x<span class="sc">+</span><span class="dv">2</span></span>
<span id="cb95-5"><a href="index.html#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(x)</span>
<span id="cb95-6"><a href="index.html#cb95-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(x)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb95-7"><a href="index.html#cb95-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">2</span>,<span class="dv">2</span>)</span>
<span id="cb95-8"><a href="index.html#cb95-8" aria-hidden="true" tabindex="-1"></a><span class="fu">log10</span>(<span class="dv">100</span>)</span>
<span id="cb95-9"><a href="index.html#cb95-9" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span>  <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">4</span>,<span class="dv">3</span>)</span>
<span id="cb95-10"><a href="index.html#cb95-10" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(y)</span>
<span id="cb95-11"><a href="index.html#cb95-11" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">c</span>(<span class="st">&quot;a&quot;</span>,<span class="st">&quot;b&quot;</span>,<span class="st">&quot;c&quot;</span>))</span>
<span id="cb95-12"><a href="index.html#cb95-12" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(y)</span>
<span id="cb95-13"><a href="index.html#cb95-13" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(y)</span>
<span id="cb95-14"><a href="index.html#cb95-14" aria-hidden="true" tabindex="-1"></a><span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">13</span>,<span class="at">by=</span><span class="dv">3</span>)</span></code></pre></div>
<p><strong>3)</strong> (<strong>helt baserende viden</strong>) Kør følgende kode til at åbne nogle af de indbygget datasæt, som vi bruger i kurset.
* Prøve <code>head()</code>, <code>nrow()</code>, <code>summary()</code> osv.
* Prøve også fk. <code>?cars</code> for at se en beskrivelse.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="index.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb96-2"><a href="index.html#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(cars)</span>
<span id="cb96-3"><a href="index.html#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ToothGrowth)</span>
<span id="cb96-4"><a href="index.html#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(sleep)</span>
<span id="cb96-5"><a href="index.html#cb96-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(chickwts)</span>
<span id="cb96-6"><a href="index.html#cb96-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb96-7"><a href="index.html#cb96-7" aria-hidden="true" tabindex="-1"></a><span class="co">#se her for andre:</span></span>
<span id="cb96-8"><a href="index.html#cb96-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="at">help =</span> <span class="st">&quot;datasets&quot;</span>)</span></code></pre></div>
<p><strong>4)</strong> (<strong>baserende plots</strong>) Jeg giver nogle muligheder for datasættet “iris”. Prøv også at bruge nogle af de andre indbyggede datasæt, som du har indlæst.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="index.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(iris<span class="sc">$</span>Sepal.Length,iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb97-2"><a href="index.html#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(iris<span class="sc">$</span>Sepal.Width)</span>
<span id="cb97-3"><a href="index.html#cb97-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(iris<span class="sc">$</span>Sepal.Length<span class="sc">~</span>iris<span class="sc">$</span>Species)</span></code></pre></div>
<p>Du kan også gøre plottene lidt pænere ved at give dem en titel og navne på akserne. Prøv at kigge på dokumentationen for plot() ved at skrive <code>?plot</code> i R-konsollen. Du kan tilføje <code>ylab</code>, <code>xlab</code> og <code>main</code> (titel) i én af plottene. Prøv også at eksperimentere med farver ved at bruge <code>col</code>. Bemærk dog, at vi vil ændre måden at lave plottene på, når vi begynder at bruge <code>ggplot2</code>.</p>
<p><strong>5)</strong> (<strong>dataframes</strong>) Brug datasættet <code>cars</code> (<code>data(cars)</code>) til at:</p>
<ul>
<li>Lav et scatter plot med speed på x-aksen og dist på y-aksen</li>
<li>Tilføj en ny kolon med følgende kode:</li>
</ul>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="index.html#cb98-1" aria-hidden="true" tabindex="-1"></a>cars<span class="sc">$</span>fast <span class="ot">&lt;-</span> cars<span class="sc">$</span>speed<span class="sc">&gt;</span><span class="dv">15</span></span></code></pre></div>
<ul>
<li>Brug <code>mean</code> på den nye kolon <code>fast</code> for at finde ud af proportionen af biler, der er hurtige</li>
<li>Beregn gennemsnitsværdien af variablen <code>dist</code> for hurtige biler og ikke-hurtige biler hver for sig (brug funktionen <code>tapply</code>). Gem resultatet med <code>&lt;-</code>.</li>
<li>Brug <code>barplot</code> til at lave et plot af den gennemsnitlige <code>dist</code> for hurtige og ikke-hurtige biler.</li>
</ul>
<p><strong>6)</strong> (<strong>dataframes</strong>) En dataframe kan indeholde forskellige datatype (i modsætning til en matrix). Lav en ny dataframe (funktionen <code>data.frame()</code>) med tre kolonner, som hedder “navn”, “alder” og “yndlings_farve” (du kan finde på værdierne selv). Sørg for, at din dataframe har 4 rækker.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="index.html#cb99-1" aria-hidden="true" tabindex="-1"></a>mydf <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;navn&quot;</span><span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;alice&quot;</span>,<span class="st">&quot;freddy&quot;</span>, ... ), <span class="st">&quot;alder&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(...), ...) <span class="co">#not run, slette &quot;...&quot; og skrive videre</span></span>
<span id="cb99-2"><a href="index.html#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(mydf) <span class="co"># fire række og tre kolonner</span></span>
<span id="cb99-3"><a href="index.html#cb99-3" aria-hidden="true" tabindex="-1"></a>mydf</span></code></pre></div>
<p><strong>7)</strong> (<strong>dataframes</strong>) Tilføj en ny kolon <code>random</code> til din oprettede dataframe - hvor værdierne kommer fra en normalfordeling med et gennemsnit på 5 og standardafvigelse på 1 (bruge funktionen <code>rnorm()</code>).</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="index.html#cb100-1" aria-hidden="true" tabindex="-1"></a>mydf<span class="sc">$</span>random <span class="ot">&lt;-</span> <span class="co">#??</span></span></code></pre></div>
<!-- 5) (**dataframes**) Lav en `data.frame` (dataframe) med to kolonner og 12 observationer. Den ene varible skal være tilfældige data fra en normal fordeling (bruge funktionen `rnorm`) med et gennemsnit på 5 og varians på 1, den anden variable skal veksle mellem "blue" og "red" (bruge `rep(c("blue","red","yellow"),4)`). -->
<!-- ```{r,eval=F} -->
<!-- set.seed(83902) #some seed so everyone's result is the same -->
<!-- mydf <- data.frame("value"= rnorm(12,5,1), "colour" = rep(c("blue","red","yellow"),4)) -->
<!-- dim(mydf) #otte rækker og tre kolonner -->
<!-- mydf -->
<!-- ``` -->
<p><strong>8)</strong> (<strong>delmængder af dataframes</strong>) Åbn datasættet “ToothGrowth” med følgende kode:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="index.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ToothGrowth&quot;</span>)</span>
<span id="cb101-2"><a href="index.html#cb101-2" aria-hidden="true" tabindex="-1"></a>?ToothGrowth</span></code></pre></div>
<ul>
<li>Find delmængden af datasættet således at diet (variablen <code>supp</code>) er “OJ” og længden (variablen <code>len</code>) er større end 15.</li>
</ul>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="index.html#cb102-1" aria-hidden="true" tabindex="-1"></a>newdf <span class="ot">&lt;-</span> ToothGrowth[<span class="co">#skrive her til at lave subset af observationerne,]</span></span></code></pre></div>
<ul>
<li>Hvor mange rækker er der i den nye data frame <code>newdf</code>?</li>
<li>Hvor mange unikke værdier er der i variablen <code>dose</code> (brug funktionen <code>unique</code>) ?</li>
<li>Find delmængden af datasættet <code>ToothGrowth</code>, hvor variablen <code>dose</code> er 0.5 eller 2.0 (hint: brug <code>%in%</code> eller <code>|</code>) og <code>supp</code> er “VC”.</li>
<li>Beregn den gennemsnitlige længde for observationerne i delmængden.</li>
</ul>
</div>
<div id="kort-analyse-med-reaktionstider" class="section level3 hasAnchor" number="1.12.3">
<h3><span class="header-section-number">1.12.3</span> Kort analyse med reaktionstider<a href="index.html#kort-analyse-med-reaktionstider" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>9)</strong> (<strong>indlæse data</strong>) Åbn en fil på Absalon ved navn “reactions.txt” ved at bruge funktionen <code>read.table()</code> og gem resultatet i variablen <code>data</code>. Husk at tjekke, om filen indeholder variabelnavne og brug <code>header=T</code> hvis nødvendigt.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="index.html#cb103-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> ... <span class="co">#replace ...</span></span></code></pre></div>
<p><strong>10)</strong> (<strong>factor variabler</strong>) Variablerne <code>subject</code> og <code>time</code> blev indlæst som henholdsvis <strong>int</strong> (heltal) og <strong>chr</strong> (character) datatyper, men de skal i stedet være <strong>factor</strong> variabler. Brug funktionen <code>as.factor()</code> til at konvertere dem til factor variabler.</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="index.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co">#gør subject til en faktor</span></span>
<span id="cb104-2"><a href="index.html#cb104-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>subject <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data<span class="sc">$</span>subject) </span>
<span id="cb104-3"><a href="index.html#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="index.html#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="do">## gør den samme her for time:</span></span></code></pre></div>
<ul>
<li>Hvor mange niveauer er der i hver af de to variabler efter konvertering til faktorvariabler? Prøv funktionerne <code>levels()</code> eller <code>nlevels()</code>.</li>
</ul>
<p><strong>11)</strong> (<strong>delmængder af dataframes</strong>)</p>
<p>Lav to delmængder af det ovenstående datasæt ved at:</p>
<ul>
<li>oprette en delmængde til alle observationer fra tidspunktet “before” ved at vælge rækkerne i dataframen hvor data$time == “before”</li>
<li>oprette en delmængde til alle observationer fra tidspunktet “after”.</li>
</ul>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="index.html#cb105-1" aria-hidden="true" tabindex="-1"></a>RT_before <span class="ot">&lt;-</span> data[<span class="co">#skrive her , ]</span></span>
<span id="cb105-2"><a href="index.html#cb105-2" aria-hidden="true" tabindex="-1"></a>RT_after <span class="ot">&lt;-</span> <span class="co">#skrive her</span></span></code></pre></div>
<ul>
<li>Opret en yderligere delmængde, som viser alle observationer fra tidspunktet “before” med en reaktionstid på mindst 800.
<ul>
<li>Hvor mange personer er der i denne delmængde?</li>
</ul></li>
</ul>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="index.html#cb106-1" aria-hidden="true" tabindex="-1"></a>RT_before_mindst800 <span class="ot">&lt;-</span> <span class="co">#skrive her</span></span></code></pre></div>
<p><strong>12)</strong> (<strong>mean og tapply</strong>) Benyt funktionen <code>mean()</code> til at beregne den gennemsnitlige reaktionstid (variablen <code>RT</code>) for “before” og “after” delmængderne.</p>
<ul>
<li>Brug funktionen <code>tapply()</code> på det oprindelige datasæt data for at beregne den samme middelværdi med mindre kode.</li>
</ul>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="index.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(<span class="co">#skrive her,#skrive her,#skrive her)</span></span></code></pre></div>
<ul>
<li>Er reaktionstiderne blevet hurtigere eller langsommere i gennemsnit?</li>
</ul>
<p><strong>13)</strong> (<strong>beregn forskellen og mean</strong>)</p>
<p>Bemærk, at datasættet er ‘paired’ - målingerne er lavet på de samme personer både “before” og “after”.</p>
<ul>
<li>Opret en vector <code>diff</code>, der indeholder forskellene i reaktionstiderne mellem “before” og “after” for hver person.</li>
<li>Beregn den gennemsnitlige forskel i rekationstiderne.</li>
</ul>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="index.html#cb108-1" aria-hidden="true" tabindex="-1"></a>diff <span class="ot">&lt;-</span> <span class="co">#change in reaction time between before and after</span></span>
<span id="cb108-2"><a href="index.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(diff)</span></code></pre></div>
<ul>
<li>Tjek, om tegnet på middelværdien stemmer overens med din konklusion fra <strong>11)</strong> - hvis den er positiv, betyder det, at reaktionstiderne er blevet langsommere.</li>
</ul>
<p><strong>14)</strong> (<strong>lav t-test i R</strong>) Lav en t-test (funktionen <code>t.test()</code>) for at teste hypotesen om, at den gennemsnitslige forskel i reaktionstiderne mellem “before” og “after” er forskellig fra 0.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="index.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="co">#skrive her..)</span></span></code></pre></div>
<p>Find følgende i outputtet fra R:</p>
<ul>
<li>Hvor er test-statistik <code>t</code>?</li>
<li>Hvor er p-værdien?</li>
<li>Hvad er alternativhypotesen?</li>
</ul>
<p>Husk at skrive en kort sætning med din endelige konklusioner.</p>
</div>
<div id="øvelse-med-co2" class="section level3 hasAnchor" number="1.12.4">
<h3><span class="header-section-number">1.12.4</span> Øvelse med CO2<a href="index.html#øvelse-med-co2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>15)</strong> (<strong>t-test med CO2</strong>)</p>
<ul>
<li>Indlæs datasættet med kommandoen <code>data(CO2)</code></li>
<li>Opret en delmængde med kun observationer for planten “Qn1”</li>
<li>Beregn den gennemsnitlige optagelse (variablen <code>uptake</code>) for hvert behandlingstype (variablen <code>Treatment</code>) i din delmængde ved hjælp af <code>tapply()</code>-funktionen.</li>
<li>Udfør en t-test ved hjælp af <code>t.test()</code>-funktionen for at sammenligne optagelsen mellem de to behandlinger i din delmængde.</li>
<li>Skriv en kort sætning med din konklusion.</li>
</ul>
</div>
<div id="ekstra-øvelser-med-statistik-tests" class="section level3 hasAnchor" number="1.12.5">
<h3><span class="header-section-number">1.12.5</span> Ekstra øvelser med statistik tests<a href="index.html#ekstra-øvelser-med-statistik-tests" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>16)</strong> (<strong>Chi-sq</strong>) Kør følgende kode til at få en tabel (selve koden er ikke vigtigt):</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="index.html#cb110-1" aria-hidden="true" tabindex="-1"></a>mytable <span class="ot">&lt;-</span> <span class="fu">structure</span>(<span class="fu">c</span>(80L, 97L, 372L, 136L, 87L, 119L), <span class="at">.Dim =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">2</span>, <span class="at">.Dimnames =</span> <span class="fu">structure</span>(<span class="fu">list</span>(</span>
<span id="cb110-2"><a href="index.html#cb110-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">&quot;First&quot;</span>, <span class="st">&quot;Second&quot;</span>, <span class="st">&quot;Third&quot;</span>), <span class="fu">c</span>(<span class="st">&quot;Died&quot;</span>, <span class="st">&quot;Survived&quot;</span>)), <span class="at">.Names =</span> <span class="fu">c</span>(<span class="st">&quot;Class&quot;</span>, <span class="st">&quot;Survival&quot;</span>)), <span class="at">class =</span> <span class="st">&quot;table&quot;</span>)</span>
<span id="cb110-3"><a href="index.html#cb110-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-4"><a href="index.html#cb110-4" aria-hidden="true" tabindex="-1"></a>mytable</span></code></pre></div>
<pre><code>##         Survival
## Class    Died Survived
##   First    80      136
##   Second   97       87
##   Third   372      119</code></pre>
<p>Tabellen angiver antallet af passagerer ombord skibet ‘Titanic’, som sank den 15. april 1912 efter et sammenstød med et isbjerg 600 km sydøst for Halifax, Nova Scotia i Canada. Tabellen er opdelt i tre klasser (førsteklasse, andenklasse, tredjeklasse) og viser antallet af passagerer, som overlevede tragedien og antallet af passagerer, som døde.</p>
<ul>
<li><p>Benyt funktionen <code>chisq.test()</code> på tabellen.</p></li>
<li><p>Hvad er nulhypotesen til testen?</p></li>
<li><p>Er testen signifikant?</p></li>
<li><p>Er passagerenes klasse og deres chance for at overleve tragedien uafhængige af hinanden?</p></li>
<li><p>Hvilken af de tre klasse havde den bedste chance for at overleve?</p></li>
</ul>
<p>OBS: Vi kommer til at arbejde meget mere med datasættet <code>Titanic</code> i emnet Tidyverse - dag 1!</p>
<p><strong>17)</strong> (<strong>Korrelation analyse</strong>) Åbn datasættet <code>trees</code> og lav et scatter plot med variablen <code>Girth</code> på x-aksen og variablen <code>Volume</code> på y-aksen.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="index.html#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb112-2"><a href="index.html#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(trees)</span></code></pre></div>
<ul>
<li>Anvend funktionen <code>cor.test</code> for at teste, om der er en signifikant korrelation mellem de to variabler. Brug <code>method = "pearson"</code> (det er dog faktisk default)</li>
</ul>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="index.html#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(???, ???,<span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<ul>
<li>Hvad er korrelationen mellem <code>Girth</code> og <code>Volume</code>?</li>
<li>Hvad er p-værdien? Er den signifikant?</li>
</ul>
<p><strong>18)</strong> (<strong>ANOVA</strong>) OBS: hvis du føler dig utryg med funktionen <code>lm()</code> - der kommer en video om det i morgen (i forbindelse med emnet Rmarkdown).</p>
<p>Kør følgende kode til at lave variansanalyse, der tester hulhypotesen hvor den gennemsnitlige værdi af variablen <code>Sepal.Width</code> er ens for hver af de tre arter (variablen <code>Species</code>) fra datasættet <code>iris</code>:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="index.html#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris)</span>
<span id="cb114-2"><a href="index.html#cb114-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-3"><a href="index.html#cb114-3" aria-hidden="true" tabindex="-1"></a><span class="co">#model under H0: no difference according to group variable Species (1 just means &quot;fit overall mean&quot;)</span></span>
<span id="cb114-4"><a href="index.html#cb114-4" aria-hidden="true" tabindex="-1"></a>model_h0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>iris) </span>
<span id="cb114-5"><a href="index.html#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="index.html#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="co">#model under H1: each level of group variable Species has its own mean</span></span>
<span id="cb114-7"><a href="index.html#cb114-7" aria-hidden="true" tabindex="-1"></a>model_h1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Width <span class="sc">~</span> Species, <span class="at">data=</span>iris) </span>
<span id="cb114-8"><a href="index.html#cb114-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-9"><a href="index.html#cb114-9" aria-hidden="true" tabindex="-1"></a><span class="co">#compare two models - significant p-value equates to choosing H1 model</span></span>
<span id="cb114-10"><a href="index.html#cb114-10" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_h0,model_h1)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Sepal.Width ~ 1
## Model 2: Sepal.Width ~ Species
##   Res.Df    RSS Df Sum of Sq     F    Pr(&gt;F)    
## 1    149 28.307                                 
## 2    147 16.962  2    11.345 49.16 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Kig på outputtet:</p>
<ul>
<li>Hvilken model reflekterer nulhypotesen?</li>
<li>Hvilken model reflekterer alternativhypotesen?</li>
<li>Hvor er p-værdien?</li>
<li>Er der en signifikant forskel i den gennemsnitlige <code>Sepal.Width</code> efter de forskellige <code>Species</code>?</li>
</ul>
<p>Brug funktionen <code>tapply</code> for at finde ud af, hvad er den middelværdi <code>Sepal.Width</code> til hver af de tre arter.</p>
<p><strong>19)</strong> (<strong>ANOVA</strong>) Lav en lignende analyse på datasættet <code>chickwts</code> for at svare på spørgsmålet:</p>
<ul>
<li>Er der en forskel i den gennemsnitlige vægt (variablen <code>weight</code>) efter fodertypen (variablen <code>feed</code>)? Med andre ord er vægt afhængig af fodertypen?</li>
</ul>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="index.html#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(chickwts)</span></code></pre></div>
<p><strong>OBS - hvis du er usikker med linær regression gennemgå gerne videoerne til emnet R Markdown og kom tilbage til følgende spørgsmål</strong></p>
<p><strong>20)</strong> (<strong>Lineær regression</strong>)</p>
<ul>
<li>Brug <code>lm</code> til at lave en simpel lineær regression, således at respons variablen <code>Volume</code> er afhængig af variablen <code>Girth</code> (datasæstet <code>trees</code>).</li>
</ul>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="index.html#cb117-1" aria-hidden="true" tabindex="-1"></a>mylm <span class="ot">&lt;-</span> <span class="fu">lm</span>(???, <span class="at">data=</span>trees) </span></code></pre></div>
<p>Brug <code>summary</code> på din model for at finde følgende værdier:</p>
<ul>
<li>Hvad er r.squared? (multiple)</li>
<li>Er variablen <code>Girth</code> signifikant?</li>
<li>Hvad er ligningen på den bedste rette linje (husk formen y = ax + b)?</li>
</ul>
<p><strong>21)</strong> (<strong>Kort intro til multiple lineær regression</strong>) Tag ovenstående model og tilføj variablen <code>Height</code> som en ekstra prediktær (uafhængig) variabel i modellen med en “+” tegn:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="index.html#cb118-1" aria-hidden="true" tabindex="-1"></a>mylm_height <span class="ot">&lt;-</span> <span class="fu">lm</span>(??? <span class="sc">~</span> ??? <span class="sc">+</span> ???, <span class="at">data=</span>trees) </span>
<span id="cb118-2"><a href="index.html#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mylm_height)</span></code></pre></div>
<p><em>Bemærk at det ikke betyder, at de to variabler skal lægges sammen, men at vi gerne vil have både variablerne i modellen som uafhængig variabler (med andre ord er <code>Volume</code> afhængig af både <code>Girth</code> og <code>Height</code>).</em></p>
<p>Benyt <code>summary</code> på modellen og prøv at finde følgende:</p>
<ul>
<li>Hvad er den den (multiple) r.squared værdi?</li>
<li>Hvor meget ændre den (multiple) r.squared værdi i forhold til modellen med kun variablen <code>Girth</code>?</li>
<li>Er <code>Volume</code> signifikant afhængig af <code>Height</code> (efter at man har taget højde for <code>Girth</code>)?</li>
</ul>
<p>Brug funktionen <code>anova</code> til at sammenligne modellen uden <code>Height</code> med modellen med <code>Height</code></p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="index.html#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(<span class="co">#model without height,#model with height)</span></span></code></pre></div>
<p>Bemærk, at i dette tilfælde er p-værdien fra ANOVA samme p-værdi fra <code>summary(mylm_height)</code>.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="rmarkdown.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["visualisering_22.pdf", "visualisering_22.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
